/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
"use strict";
/**
 * favoriteService/index.ts - 收藏服务（TypeScript 源文件 - Sprint 46 迁移）
 *
 * 业务功能：
 *   - add - 添加收藏（防重）
 *   - remove - 取消收藏
 *   - list - 拉取收藏列表（分页）
 *
 * 迁移目标：
 *   - 强类型化 3 个 action handler 签名
 *   - 复用 AuthLike / CloudEvent / CloudContext 公共类型
 *   - 抽离 FavoriteTargetType 联合类型与 COLLECTION 常量
 *
 * 编译方式：
 *   npx --yes -p typescript@5.4.5 tsc -p tsconfig.favoriteService.json
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.main = exports.getFavorites = exports.removeFavorite = exports.addFavorite = exports.MAX_PAGE_SIZE = exports.DEFAULT_PAGE_SIZE = exports.COLLECTION = void 0;
// =====================================================================
// 内部模块初始化
// =====================================================================
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { initCloud, handleSuccess, handleError, ERROR_CODES } = require('./common/utils');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createLogger } = require('./common/logger');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { verifyAuth } = require('./common/auth-middleware');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { err } = require('./common/errors');
const { cloud, db } = initCloud();
const logger = createLogger('favoriteService');
const _ = db.command;
// =====================================================================
// 常量
// =====================================================================
exports.COLLECTION = 'favorites';
exports.DEFAULT_PAGE_SIZE = 20;
exports.MAX_PAGE_SIZE = 100;
// =====================================================================
// Action 1：添加收藏
// =====================================================================
async function addFavorite(event, openid, dbInstance) {
    const { targetType, targetId } = event;
    if (!targetType || !targetId) {
        throw err('INVALID_PARAMS', '缺少收藏目标信息');
    }
    const existing = await dbInstance.collection(exports.COLLECTION)
        .where({ ownerId: openid, targetType, targetId })
        .limit(1)
        .get();
    if (existing.data && existing.data.length > 0) {
        throw err('BUSINESS_ERROR', '已经收藏过了');
    }
    await dbInstance.collection(exports.COLLECTION).add({
        data: {
            ownerId: openid,
            targetType,
            targetId,
            createdAt: dbInstance.serverDate(),
        },
    });
    return handleSuccess(null, '收藏成功');
}
exports.addFavorite = addFavorite;
// =====================================================================
// Action 2：取消收藏
// =====================================================================
async function removeFavorite(event, openid, dbInstance) {
    const { targetType, targetId } = event;
    if (!targetType || !targetId) {
        throw err('INVALID_PARAMS', '缺少收藏目标信息');
    }
    await dbInstance.collection(exports.COLLECTION)
        .where({ ownerId: openid, targetType, targetId })
        .remove();
    return handleSuccess(null, '取消收藏成功');
}
exports.removeFavorite = removeFavorite;
// =====================================================================
// Action 3：拉取收藏列表
// =====================================================================
async function getFavorites(event, openid, dbInstance) {
    const { targetType, page = 1, pageSize = exports.DEFAULT_PAGE_SIZE } = event;
    const where = { ownerId: openid };
    if (targetType) {
        where.targetType = targetType;
    }
    const countRes = await dbInstance.collection(exports.COLLECTION).where(where).count();
    const listRes = await dbInstance.collection(exports.COLLECTION)
        .where(where)
        .orderBy('createdAt', 'desc')
        .skip((page - 1) * pageSize)
        .limit(pageSize)
        .get();
    return handleSuccess({
        list: listRes.data,
        total: countRes.total,
        page: page,
        pageSize: pageSize,
    });
}
exports.getFavorites = getFavorites;
// =====================================================================
// Handlers 聚合 + Main 入口
// =====================================================================
const handlers = {
    add: addFavorite,
    remove: removeFavorite,
    list: getFavorites,
};
async function main(event, _context) {
    const { action } = event;
    try {
        const auth = await verifyAuth(event, { requireLogin: true });
        logger.info(action, { openid: auth.openid });
        if (!action || !handlers[action]) {
            throw err('INVALID_PARAMS', `未知的 action: ${action}`);
        }
        return await handlers[action](event, auth.openid, db);
    }
    catch (error) {
        logger.error(action, error);
        const code = error.code || ERROR_CODES.BUSINESS;
        return handleError(error, error.message, code);
    }
}
exports.main = main;
// =====================================================================
// Runtime shim（CommonJS 兼容）
// =====================================================================
const _mod = module;
_mod.exports = {
    main,
    addFavorite,
    removeFavorite,
    getFavorites,
    COLLECTION: exports.COLLECTION,
    DEFAULT_PAGE_SIZE: exports.DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE: exports.MAX_PAGE_SIZE,
};
_mod.exports.default = _mod.exports;
exports.default = {
    main,
    addFavorite,
    removeFavorite,
    getFavorites,
    COLLECTION: exports.COLLECTION,
    DEFAULT_PAGE_SIZE: exports.DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE: exports.MAX_PAGE_SIZE,
};
