/**
 * Sprint 49 - boarding-state-machine.js → .ts 迁移验证测试
 *
 * 目标：
 *   1. 验证 cloudfunctions/orderService/common/boarding-state-machine.ts 存在且为源文件
 *   2. 验证编译产物 boarding-state-machine.js / .d.ts 存在
 *   3. 验证 .d.ts 包含核心导出
 *   4. 验证 tsconfig.orderService.json 包含新文件
 *   5. 验证编译产物的功能与原 .js 行为一致
 *   6. 验证运行时导出与 .ts 源一致
 */

const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const ORDER_COMMON = path.join(ROOT, 'cloudfunctions', 'orderService', 'common')
const SRC = path.join(ORDER_COMMON, 'boarding-state-machine.ts')
const JS = path.join(ORDER_COMMON, 'boarding-state-machine.js')
const DTS = path.join(ORDER_COMMON, 'boarding-state-machine.d.ts')

describe('Sprint 49: boarding-state-machine.js → .ts 迁移', () => {
  test('boarding-state-machine.ts 源文件应存在', () => {
    expect(fs.existsSync(SRC)).toBe(true)
  })

  test('编译产物 boarding-state-machine.js 应存在', () => {
    expect(fs.existsSync(JS)).toBe(true)
  })

  test('类型声明 boarding-state-machine.d.ts 应存在', () => {
    expect(fs.existsSync(DTS)).toBe(true)
  })

  test('.js 编译产物应含 eslint-disable 标记', () => {
    const js = fs.readFileSync(JS, 'utf8')
    expect(js).toContain('/* eslint-disable -- auto-generated by tsc')
  })

  test('.d.ts 应包含核心导出', () => {
    const dts = fs.readFileSync(DTS, 'utf8')
    expect(dts).toContain('boardingOrderStateMachine')
    expect(dts).toContain('getTargetStatusByOperation')
    expect(dts).toContain('canPerformOperation')
    expect(dts).toContain('BOARDING_OPERATION_TARGET')
    expect(dts).toContain('BoardingState')
    expect(dts).toContain('BoardingOperation')
  })

  test('tsconfig.orderService.json 应包含 boarding-state-machine.ts', () => {
    const cfg = JSON.parse(
      fs.readFileSync(path.join(ROOT, 'tsconfig.orderService.json'), 'utf8')
    )
    expect(cfg.include).toContain(
      'cloudfunctions/orderService/common/boarding-state-machine.ts'
    )
  })

  test('build:orderService 应处理 boarding-state-machine.js（build-all-services.js TARGETS）', () => {
    const buildScript = fs.readFileSync(
      path.join(ROOT, 'scripts', 'build-all-services.js'),
      'utf8'
    )
    expect(buildScript).toMatch(/boarding-state-machine\.js/)
  })

  test('编译后的 .js 仍能正确导出所有公共 API', () => {
    const api = require(JS)
    expect(api.boardingOrderStateMachine).toBeDefined()
    expect(typeof api.getTargetStatusByOperation).toBe('function')
    expect(typeof api.canPerformOperation).toBe('function')
    expect(api.BOARDING_OPERATION_TARGET).toBeDefined()
  })

  test('boardingOrderStateMachine 应保持 9 个状态（Sprint 49 迁移）', () => {
    const { boardingOrderStateMachine } = require(JS)
    expect(boardingOrderStateMachine.initial).toBe('pending_payment')
    expect(boardingOrderStateMachine.states.sort()).toEqual(
      ['cancelled', 'completed', 'confirmed', 'deleted', 'in_progress', 'paid', 'pending_payment', 'refunded', 'rejected']
    )
  })

  test('boardingOrderStateMachine 转移表应保持新行为（Sprint 49 迁移）', () => {
    const { boardingOrderStateMachine } = require(JS)
    expect(boardingOrderStateMachine.canTransition('pending_payment', 'paid')).toBe(true)
    expect(boardingOrderStateMachine.canTransition('pending_payment', 'cancelled')).toBe(true)
    expect(boardingOrderStateMachine.canTransition('paid', 'confirmed')).toBe(true)
    expect(boardingOrderStateMachine.canTransition('paid', 'rejected')).toBe(true)
    expect(boardingOrderStateMachine.canTransition('confirmed', 'in_progress')).toBe(true)
    expect(boardingOrderStateMachine.canTransition('in_progress', 'completed')).toBe(true)
    expect(boardingOrderStateMachine.isTerminal('completed')).toBe(true)
    expect(boardingOrderStateMachine.isTerminal('rejected')).toBe(true)
    expect(boardingOrderStateMachine.isTerminal('cancelled')).toBe(true)
    expect(boardingOrderStateMachine.isTerminal('refunded')).toBe(true)
    expect(boardingOrderStateMachine.canTransition('pending_payment', 'confirmed')).toBe(false)
  })

  test('BOARDING_OPERATION_TARGET 应保持原映射', () => {
    const { BOARDING_OPERATION_TARGET } = require(JS)
    expect(Object.keys(BOARDING_OPERATION_TARGET).sort()).toEqual(
      ['cancel', 'complete', 'confirm', 'reject']
    )
    expect(BOARDING_OPERATION_TARGET.confirm).toBe('confirmed')
    expect(BOARDING_OPERATION_TARGET.reject).toBe('rejected')
    expect(BOARDING_OPERATION_TARGET.complete).toBe('completed')
    expect(BOARDING_OPERATION_TARGET.cancel).toBe('cancelled')
  })

  test('getTargetStatusByOperation 行为应保持不变', () => {
    const { getTargetStatusByOperation } = require(JS)
    expect(getTargetStatusByOperation('confirm')).toBe('confirmed')
    expect(getTargetStatusByOperation('reject')).toBe('rejected')
    expect(getTargetStatusByOperation('complete')).toBe('completed')
    expect(getTargetStatusByOperation('cancel')).toBe('cancelled')
    expect(getTargetStatusByOperation('unknown')).toBeNull()
    expect(getTargetStatusByOperation('')).toBeNull()
    expect(getTargetStatusByOperation(null)).toBeNull()
  })

  test('canPerformOperation 行为应匹配新状态机（Sprint 49 迁移）', () => {
    const { canPerformOperation } = require(JS)
    expect(canPerformOperation('pending_payment', 'confirm')).toBe(false) // 需先 paid 再 confirm
    expect(canPerformOperation('paid', 'confirm')).toBe(true) // paid → confirmed 合法
    expect(canPerformOperation('pending_payment', 'complete')).toBe(false)
    expect(canPerformOperation('confirmed', 'complete')).toBe(true)
    expect(canPerformOperation('in_progress', 'confirm')).toBe(false)
    expect(canPerformOperation('completed', 'cancel')).toBe(false)
    expect(canPerformOperation('pending_payment', 'unknown')).toBe(false)
    expect(canPerformOperation(null, 'confirm')).toBe(false)
    expect(canPerformOperation('pending_payment', null)).toBe(false)
  })
})
