/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
"use strict";
/**
 * activityService/index.ts - 活动服务主入口（TypeScript 源文件 - Sprint 38 迁移）
 *
 * 业务功能：
 *   - 活动管理（CRUD + 自动状态更新）
 *   - 活动报名（带风控前置 + 优惠券）
 *   - 活动支付订单（创建 + 确认）
 *   - 报名管理（详情、列表、导出）
 *   - 合作伙伴视角（活动报名列表、活动订单列表、CSV 导出）
 *
 * 共 13 个 action：
 *   1. getActivityList - 活动列表
 *   2. getActivityDetail - 活动详情
 *   3. createActivity - 创建活动
 *   4. updateActivity - 更新活动
 *   5. deleteActivity - 删除活动
 *   6. submitRegistration - 提交报名（含风控前置）
 *   7. getRegistrationDetail - 报名详情
 *   8. getRegistrationList - 报名列表
 *   9. createActivityPaymentOrder - 创建活动支付订单
 *  10. confirmActivityPayment - 确认活动支付
 *  11. getActivityRegistrations - 活动报名列表（合作伙伴）
 *  12. exportActivityRegistrations - 导出活动报名（CSV）
 *  13. getActivityOrders - 活动订单列表（合作伙伴）
 *
 * 迁移目标：
 *   - 强类型化所有 db 操作、handler 签名、返回结构
 *   - 复用 AuthLike / CloudEvent / CloudContext 公共类型
 *   - 与 adminService / partnerService / userService 保持类型一致
 *
 * 编译方式：
 *   npx --yes -p typescript@5.4.5 tsc -p tsconfig.activityService.json
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.main = exports.handlers = exports.getActivityOrders = exports.exportActivityRegistrations = exports.getActivityRegistrations = exports.confirmActivityPayment = exports.createActivityPaymentOrder = exports.getRegistrationList = exports.getRegistrationDetail = exports.submitRegistration = exports.deleteActivity = exports.updateActivity = exports.createActivity = exports.getActivityDetail = exports.getActivityList = void 0;
// =====================================================================
// 内部模块初始化（require CommonJS 模块）
// =====================================================================
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { initCloud, handleSuccess, handleError, generateId, ERROR_CODES, paginate } = require('./common/utils');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createLogger } = require('./common/logger');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { verifyAuth } = require('./common/auth-middleware');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { filterFields, FIELD_WHITELISTS } = require('./common/validator');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { err, isBusinessError } = require('./common/errors');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createCommissionRecord: createCommissionRecordShared, cancelCommissionRecord } = require('./common/commission-utils');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createActivityIncomeRecords } = require('./common/service-income-utils');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { ENDPOINTS } = require('./common/config');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { detectActivityApplyRisk, mapActionToErrorCode } = require('./common/risk-control');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { withRateLimit } = require('./common/risk-rate-limit');
// Sprint 50: 限流统一 bootstrap
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { bootstrapRateLimit } = require('./common/rate-limit-bootstrap');
const { cloud, db } = initCloud();
const logger = createLogger('activityService');
const _ = db.command;
// Sprint 50: 注入全局限流存储（rate_limits + rate_limit_configs 一次注入）
try {
    bootstrapRateLimit(db, { logger });
}
catch (e) {
    logger.warn('bootstrapRateLimit failed, fallback to memory:', e && e.message);
}
// =====================================================================
// 辅助函数：风控前置
// =====================================================================
/**
 * Sprint 22: 活动报名风控前置
 *   - reject → 抛 RISK_REJECT
 *   - review → 标 pendingReview = true（不阻塞报名，运营后续抽检）
 *   - allow  → 放行
 */
async function performActivityApplyRiskCheck(ctx) {
    const { openid, activityId, amountFen } = ctx;
    let pendingReview = false;
    let riskDecision = 'RISK_PASS';
    let riskReasons = [];
    try {
        const risk = await withRateLimit({ userId: openid, type: 'activity_apply', targetId: activityId }, () => detectActivityApplyRisk({
            db,
            userId: openid,
            amountFen,
            targetId: activityId,
        }));
        riskDecision = mapActionToErrorCode(risk.action);
        riskReasons = risk.reasons;
        if (risk.action === 'reject') {
            logger.warn('activityApply.risk_reject', { userId: openid, activityId, amountFen, reasons: risk.reasons });
            throw err('RISK_REJECT', '报名被风控拦截', {
                reasons: risk.reasons,
                level: risk.level,
                activityId,
            });
        }
        if (risk.action === 'review') {
            pendingReview = true;
            logger.info('activityApply.risk_pending', { userId: openid, activityId, amountFen, reasons: risk.reasons });
        }
        else {
            const debug = logger.debug;
            if (debug) {
                debug('activityApply.risk_pass', { userId: openid, activityId });
            }
        }
    }
    catch (e) {
        if (isBusinessError(e) && (e.code === 'RATE_LIMITED' || e.code === 'RISK_REJECT')) {
            throw e;
        }
        logger.warn('activityApply.risk_control_error', { userId: openid, activityId, msg: e && e.message });
        riskDecision = 'RISK_PASS';
    }
    return { pendingReview, reasons: riskReasons, decision: riskDecision };
}
// =====================================================================
// 辅助函数：佣金记录（使用共享模块）
// =====================================================================
const createCommissionRecord = createCommissionRecordShared;
// =====================================================================
// 辅助函数：活动状态自动更新
// =====================================================================
async function autoUpdateActivityStatus() {
    try {
        const now = new Date();
        const utc = now.getTime() + (now.getTimezoneOffset() * 60000);
        const bjTime = new Date(utc + (8 * 3600000));
        const nowStr = `${bjTime.getFullYear()}-${String(bjTime.getMonth() + 1).padStart(2, '0')}-${String(bjTime.getDate()).padStart(2, '0')} ${String(bjTime.getHours()).padStart(2, '0')}:${String(bjTime.getMinutes()).padStart(2, '0')}`;
        const stoppedRes = await db.collection('activities')
            .where({ status: 'published', startTime: _.lte(nowStr) })
            .update({ data: { status: 'registration_stopped', updatedAt: db.serverDate() } });
        if (stoppedRes.updated > 0) {
            logger.info('autoUpdate.stopped', { updated: stoppedRes.updated });
        }
        // 查询即将结束的活动（用于生成佣金）
        const endingActivitiesRes = await db.collection('activities')
            .where({ status: _.in(['published', 'registration_stopped']), endTime: _.lte(nowStr) })
            .get();
        const endingActivities = endingActivitiesRes.data || [];
        // 更新活动状态为 ended
        const endedRes = await db.collection('activities')
            .where({ status: _.in(['published', 'registration_stopped']), endTime: _.lte(nowStr) })
            .update({ data: { status: 'ended', updatedAt: db.serverDate() } });
        if (endedRes.updated > 0) {
            logger.info('autoUpdate.ended', { updated: endedRes.updated });
            // 为每个结束的活动生成佣金记录和收入记录
            for (const activity of endingActivities) {
                try {
                    // 生成佣金记录（推广者的佣金）
                    await generateActivityCommissions(activity._id);
                    
                    // 生成收入记录（活动创建者的收入）
                    if (activity.createdBy) {
                        await createActivityIncomeRecords(activity._id, activity.createdBy);
                    }
                }
                catch (e) {
                    logger.error('autoUpdate.commission', { activityId: activity._id, msg: e.message });
                }
            }
        }
    }
    catch (e) {
        logger.error('autoUpdate', e);
    }
}
/**
 * 为已结束的活动生成佣金记录
 * 查询所有已确认的报名，为每个报名创建佣金
 */
async function generateActivityCommissions(activityId) {
    try {
        // 查询该活动所有已确认的报名
        const registrationsRes = await db.collection('activity_registrations')
            .where({ activityId, status: 'confirmed' })
            .get();
        const registrations = registrationsRes.data || [];
        if (registrations.length === 0) {
            logger.info('generateActivityCommissions.noRegistrations', { activityId });
            return;
        }
        // 获取所有报名对应的订单ID
        const orderIds = registrations.map(r => r.orderId).filter(Boolean);
        if (orderIds.length === 0)
            return;
        // 批量查询订单
        const ordersRes = await db.collection('orders')
            .where({ _id: _.in(orderIds), status: 'confirmed' })
            .get();
        const orders = ordersRes.data || [];
        // 为每个订单创建佣金记录
        for (const order of orders) {
            try {
                await createCommissionRecord('activity', order);
            }
            catch (e) {
                logger.warn('generateActivityCommissions.order', { orderId: order._id, msg: e.message });
            }
        }
        logger.info('generateActivityCommissions.done', { activityId, registrations: registrations.length, orders: orders.length });
    }
    catch (e) {
        logger.error('generateActivityCommissions', { activityId, msg: e.message });
    }
}
// =====================================================================
// 辅助函数：合作伙伴权限校验
// =====================================================================
async function checkPartnerPermission(openid, permission) {
    const adminRes = await db.collection('admins')
        .where({ _id: openid, status: 'active' })
        .limit(1).get();
    if (!adminRes.data || adminRes.data.length === 0) {
        throw err('PARTNER_REQUIRED', '无合作伙伴权限');
    }
    const admin = adminRes.data[0];
    const roles = admin.roles || [];
    if (roles.includes('super_admin')) {
        return admin;
    }
    const perms = admin.permissions || [];
    if (!perms.includes(permission)) {
        throw err('PERMISSION_DENIED', `权限不足：需要 ${permission} 权限`);
    }
    return admin;
}
// =====================================================================
// 辅助函数：支付参数创建
// =====================================================================
async function _createPaymentParams(openid, orderId, amount, description) {
    const wxContext = cloud.getWXContext();
    const mchId = cloud.env.MERCHANT_ID || process.env.MERCHANT_ID;
    if (!mchId) {
        throw new Error('商户号未配置');
    }
    const nonceStr = Math.random().toString(36).substr(2, 15);
    const timestamp = String(Math.floor(Date.now() / 1000));
    const body = description;
    const totalFee = Math.round(amount * 100);
    const outTradeNo = orderId;
    const cloudEnv = cloud.env;
    const notifyUrl = `https://${cloudEnv}-1300000000.ap-shanghai.tencentscf.com/payment/notify`;
    const spbillCreateIp = '127.0.0.1';
    const tradeType = 'JSAPI';
    const signStr = `appid=${wxContext.APPID}&body=${body}&mch_id=${mchId}&nonce_str=${nonceStr}&notify_url=${notifyUrl}&openid=${openid}&out_trade_no=${outTradeNo}&spbill_create_ip=${spbillCreateIp}&total_fee=${totalFee}&trade_type=${tradeType}`;
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const crypto = require('crypto');
    const merchantKey = cloud.env.MERCHANT_KEY || process.env.MERCHANT_KEY || '';
    const paySign = crypto.createHash('md5').update(`${signStr}&key=${merchantKey}`).digest('hex').toUpperCase();
    const unifiedOrderXml = `<xml>
    <appid>${wxContext.APPID}</appid>
    <body>${body}</body>
    <mch_id>${mchId}</mch_id>
    <nonce_str>${nonceStr}</nonce_str>
    <notify_url>${notifyUrl}</notify_url>
    <openid>${openid}</openid>
    <out_trade_no>${outTradeNo}</out_trade_no>
    <spbill_create_ip>${spbillCreateIp}</spbill_create_ip>
    <total_fee>${totalFee}</total_fee>
    <trade_type>${tradeType}</trade_type>
    <sign>${paySign}</sign>
  </xml>`;
    try {
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const https = require('https');
        const result = await new Promise((resolve, reject) => {
            const req = https.request(`${ENDPOINTS.WECHAT_PAY_API_BASE}${ENDPOINTS.WECHAT_PAY_UNIFIEDORDER}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/xml' },
            }, (res) => {
                let data = '';
                res.on('data', (chunk) => { data += chunk.toString(); });
                res.on('end', () => resolve(data));
            });
            req.on('error', reject);
            req.write(unifiedOrderXml);
            req.end();
        });
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const xml2js = require('xml2js');
        const xmlResult = await new Promise((resolve, reject) => {
            xml2js.parseString(result, { explicitArray: false }, (e, parsed) => {
                if (e) {
                    reject(e);
                }
                else {
                    resolve(parsed);
                }
            });
        });
        if (xmlResult.xml.return_code === 'SUCCESS' && xmlResult.xml.result_code === 'SUCCESS') {
            const prepayId = xmlResult.xml.prepay_id;
            const jsNounceStr = Math.random().toString(36).substr(2, 15);
            const jsTimestamp = String(Math.floor(Date.now() / 1000));
            const jsPackage = `prepay_id=${prepayId}`;
            const jsSignStr = `appid=${wxContext.APPID}&noncestr=${jsNounceStr}&package=${jsPackage}&signType=MD5&timeStamp=${jsTimestamp}`;
            const jsPaySign = crypto.createHash('md5').update(`${jsSignStr}&key=${merchantKey}`).digest('hex').toUpperCase();
            return {
                timeStamp: jsTimestamp,
                nonceStr: jsNounceStr,
                package: jsPackage,
                signType: 'MD5',
                paySign: jsPaySign,
            };
        }
        else {
            throw new Error(xmlResult.xml.err_code_des || xmlResult.xml.return_msg || '统一下单失败');
        }
    }
    catch (e) {
        logger.error('创建支付参数失败:', e);
        throw new Error(`创建支付参数失败: ${e.message}`);
    }
}
// =====================================================================
// Handler 1: getActivityList - 活动列表
// =====================================================================
const ACTIVITY_LIST_FIELDS = {
    _id: true, title: true, coverUrl: true, startTime: true, endTime: true,
    location: true, latitude: true, longitude: true, category: true,
    price: true, pricePerPerson: true, pricePerPet: true,
    maxParticipants: true, currentParticipants: true, status: true, createdBy: true, createdAt: true, organizer: true,
};
const REGISTRATION_LIST_FIELDS = {
    _id: true, activityId: true, openid: true, phone: true, status: true,
    totalAmount: true, createdAt: true,
};
async function getActivityList(event, context, auth) {
    const { page = 1, pageSize = 10, status, category } = event;
    const safePageSize = Math.min(Math.max(1, Number(pageSize) || 10), 100);
    logger.info('getActivityList.query', { page, pageSize: safePageSize, status, category });
    await autoUpdateActivityStatus();
    const where = {};
    if (status && status !== 'all') {
        where.status = status;
    }
    else {
        where.status = _.neq('deleted');
    }
    if (category && category !== 'all') {
        where.category = category;
    }
    const result = await paginate(db, 'activities', {
        page, pageSize: safePageSize, where,
        projection: ACTIVITY_LIST_FIELDS,
        orderBy: { field: 'createdAt', direction: 'desc' },
    });
    result.list.forEach((activity) => {
        const avatar = activity.organizer && activity.organizer.avatar;
        if (avatar && !avatar.startsWith('cloud://') && !avatar.startsWith('https://')) {
            if (activity.organizer) {
                activity.organizer.avatar = '';
                activity.organizer._avatarInvalid = true;
            }
        }
    });
    const invalidAvatarActivities = result.list.filter(a => a.organizer && a.organizer._avatarInvalid && a.createdBy);
    if (invalidAvatarActivities.length > 0) {
        const creatorOpenids = [...new Set(invalidAvatarActivities.map(a => a.createdBy).filter((id) => Boolean(id)))];
        try {
            const adminRes = await db.collection('admins').where({ _id: _.in(creatorOpenids) }).field({ avatarUrl: true, nickName: true }).get();
            const adminMap = {};
            (adminRes.data || []).forEach((a) => { if (a._id) {
                adminMap[a._id] = a;
            } });
            invalidAvatarActivities.forEach((activity) => {
                if (!activity.createdBy || !activity.organizer) {
                    return;
                }
                const admin = adminMap[activity.createdBy];
                if (admin && admin.avatarUrl && (admin.avatarUrl.startsWith('cloud://') || admin.avatarUrl.startsWith('https://'))) {
                    activity.organizer.avatar = admin.avatarUrl;
                    if (admin.nickName && activity.organizer.name === '宠团团') {
                        activity.organizer.name = admin.nickName;
                    }
                }
                delete activity.organizer._avatarInvalid;
            });
        }
        catch (e) {
            invalidAvatarActivities.forEach((a) => { if (a.organizer) {
                delete a.organizer._avatarInvalid;
            } });
        }
    }
    logger.info('getActivityList.result', { total: result.total, listCount: result.list.length });
    let myRegistrations = [];
    if (auth.openid) {
        const regRes = await db.collection('activity_registrations')
            .where({ ownerId: auth.openid, status: 'confirmed' })
            .field({ activityId: true })
            .get();
        myRegistrations = (regRes.data || []).map((r) => r.activityId).filter((id) => Boolean(id));
    }
    result.list = result.list.map((activity) => ({
        ...activity,
        joined: myRegistrations.includes(activity._id || ''),
    }));
    return handleSuccess(result, '获取成功');
}
exports.getActivityList = getActivityList;
// =====================================================================
// Handler 2: getActivityDetail - 活动详情
// =====================================================================
async function getActivityDetail(event, context, auth) {
    const { activityId } = event;
    if (!activityId) {
        throw err('INVALID_PARAMS', '缺少活动ID');
    }
    try {
        const res = await db.collection('activities').doc(activityId).get();
        let isRegistered = false;
        if (auth.openid) {
            const regRes = await db.collection('activity_registrations')
                .where({ activityId, ownerId: auth.openid, status: 'confirmed' })
                .count();
            isRegistered = regRes.total > 0;
        }
        const data = res.data;
        if (!data) {
            throw err('NOT_FOUND', '活动不存在');
        }
        const result = { ...data, isRegistered };
        if (result.organizer && result.organizer.avatar) {
            const avatar = result.organizer.avatar;
            if (!avatar.startsWith('cloud://') && !avatar.startsWith('https://')) {
                result.organizer.avatar = '';
                if (result.createdBy) {
                    try {
                        let admin = null;
                        try {
                            const adminRes = await db.collection('admins').doc(result.createdBy).field({ avatarUrl: true, nickName: true }).get();
                            admin = adminRes.data;
                        }
                        catch (e) {
                            logger.warn('getActivityDetail.admins.fetch', { createdBy: result.createdBy, code: e.errCode, msg: e.message });
                        }
                        if (admin && admin.avatarUrl && (admin.avatarUrl.startsWith('cloud://') || admin.avatarUrl.startsWith('https://'))) {
                            result.organizer.avatar = admin.avatarUrl;
                            if (admin.nickName && result.organizer.name === '宠团团') {
                                result.organizer.name = admin.nickName;
                            }
                        }
                    }
                    catch (e) {
                        logger.warn('getActivityDetail.organizer.fill', { createdBy: result.createdBy, code: e.errCode, msg: e.message });
                    }
                }
            }
        }
        if (data.createdBy && result.organizer) {
            try {
                const countRes = await db.collection('activities')
                    .where({ createdBy: data.createdBy, status: _.in(['published', 'ongoing', 'ended']) })
                    .count();
                result.organizer.activityCount = countRes.total || 0;
            }
            catch (e) {
                logger.warn('queryHostActivities', e);
                result.organizer.activityCount = 0;
            }
        }
        return handleSuccess(result, '获取成功');
    }
    catch (error) {
        return handleError(error, '活动不存在', ERROR_CODES.NOT_FOUND);
    }
}
exports.getActivityDetail = getActivityDetail;
// =====================================================================
// Handler 3: createActivity - 创建活动
// =====================================================================
async function createActivity(event, context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { title, description, coverUrl, startTime, endTime, location, latitude, longitude, maxParticipants, category, price } = event;
    if (!title) {
        throw err('INVALID_PARAMS', '缺少活动标题');
    }
    let organizer = null;
    try {
        const userRes = await db.collection('users').doc(openid).get();
        organizer = userRes.data;
    }
    catch (e) {
        logger.warn('createActivity.users.fetch', { openid, msg: e.message });
    }
    const activity = {
        title,
        description: description || '',
        coverUrl: coverUrl || '',
        images: event.images || [],
        startTime: startTime || '',
        endTime: endTime || '',
        location: location || '',
        latitude: latitude || null,
        longitude: longitude || null,
        maxParticipants: maxParticipants || 0,
        currentParticipants: 0,
        category: category || 'outdoor',
        price: (Number(event.pricePerPerson) || 0) + (Number(event.pricePerPet) || 0) || Number(price) || 0,
        pricePerPerson: Number(event.pricePerPerson) || 0,
        pricePerPet: Number(event.pricePerPet) || 0,
        contactName: event.contactName || '',
        contactPhone: event.contactPhone || '',
        wechatId: event.wechatId || '',
        status: event.status || 'draft',
        createdBy: openid,
        organizer: organizer ? {
            name: organizer.nickName || '宠团团',
            avatar: organizer.avatarUrl || '/images/default-avatar.svg',
        } : { name: '宠团团', avatar: '/images/default-avatar.svg' },
        createdAt: db.serverDate(),
        updatedAt: db.serverDate(),
    };
    activity._id = generateId('activity', openid);
    const res = await db.collection('activities').add({ data: activity });
    return handleSuccess({ id: res._id }, '创建成功');
}
exports.createActivity = createActivity;
// =====================================================================
// Handler 4: updateActivity - 更新活动
// =====================================================================
async function updateActivity(event, context, auth) {
    const { activityId } = event;
    const { openid } = auth;
    if (!activityId) {
        throw err('INVALID_PARAMS', '缺少活动ID');
    }
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const updateData = { updatedAt: db.serverDate(), ...filterFields(FIELD_WHITELISTS.activity, event) };
    const existRes = await db.collection('activities').doc(activityId).get();
    const existData = existRes.data;
    if (!existData) {
        throw err('NOT_FOUND', '活动不存在');
    }
    if (existData.createdBy !== openid) {
        try {
            await checkPartnerPermission(openid, 'activity');
        }
        catch (e) {
            throw err('PERMISSION_DENIED', '无权修改此活动');
        }
    }
    await db.collection('activities').doc(activityId).update({ data: updateData });
    // 活动取消时取消佣金记录
    if (updateData.status === 'cancelled') {
        try {
            // 查询该活动所有已确认的报名
            const registrationsRes = await db.collection('activity_registrations')
                .where({ activityId, status: 'confirmed' })
                .get();
            const registrations = registrationsRes.data || [];
            // 获取所有报名对应的订单ID
            const orderIds = registrations.map(r => r.orderId).filter(Boolean);
            if (orderIds.length > 0) {
                // 批量查询订单
                const ordersRes = await db.collection('orders')
                    .where({ _id: _.in(orderIds) })
                    .get();
                const orders = ordersRes.data || [];
                // 为每个订单取消佣金记录和收入记录
                for (const order of orders) {
                    try {
                        await cancelCommissionRecord(order._id);
                    }
                    catch (e) {
                        logger.warn('updateActivity.cancelCommissionRecord', {
                            orderId: order._id,
                            msg: e?.message
                        });
                    }
                    try {
                        const { cancelServiceIncomeRecord } = require('./common/service-income-utils');
                        await cancelServiceIncomeRecord(order._id, 'activity');
                    }
                    catch (e) {
                        logger.warn('updateActivity.cancelServiceIncomeRecord', {
                            orderId: order._id,
                            msg: e?.message
                        });
                    }
                }
                logger.info('updateActivity.cancelCommissions', {
                    activityId,
                    cancelledCount: orders.length
                });
            }
        }
        catch (e) {
            logger.warn('updateActivity.cancelCommissions.failed', {
                activityId,
                msg: e?.message
            });
        }
    }
    return handleSuccess(null, '更新成功');
}
exports.updateActivity = updateActivity;
// =====================================================================
// Handler 5: deleteActivity - 删除活动
// =====================================================================
async function deleteActivity(event, context, auth) {
    const { activityId } = event;
    const { openid } = auth;
    if (!activityId) {
        throw err('INVALID_PARAMS', '缺少活动ID');
    }
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const existRes = await db.collection('activities').doc(activityId).get();
    const existData = existRes.data;
    if (!existData) {
        throw err('ACTIVITY_NOT_FOUND', '活动不存在');
    }
    if (existData.status === 'published') {
        throw err('INVALID_PARAMS', '已发布的活动不能删除');
    }
    if (existData.createdBy !== openid) {
        try {
            await checkPartnerPermission(openid, 'activity');
        }
        catch (e) {
            throw err('PERMISSION_DENIED', '无权删除此活动');
        }
    }
    const regCountRes = await db.collection('activity_registrations')
        .where({ activityId })
        .count();
    const regCount = regCountRes.total || 0;
    if (regCount > 0) {
        throw err('ACTIVITY_HAS_REGISTRATIONS', `该活动已有 ${regCount} 人报名，无法删除`, { regCount });
    }
    await db.collection('activities').doc(activityId).remove();
    return handleSuccess(null, '删除成功');
}
exports.deleteActivity = deleteActivity;
// =====================================================================
// Handler 6: submitRegistration - 提交报名（含风控前置）
// =====================================================================
async function submitRegistration(event, context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { activityId, pets, phone, notes, friends, petIds, totalAmount, originalAmount, couponId, couponDiscount, participantCount } = event;
    if (!activityId) {
        throw err('INVALID_PARAMS', '缺少活动ID');
    }
    if (!pets || !Array.isArray(pets) || pets.length === 0) {
        throw err('INVALID_PARAMS', '请选择参与的宠物');
    }
    if (!phone) {
        throw err('INVALID_PARAMS', '请填写联系电话');
    }
    const transaction = await db.startTransaction();
    try {
        const activityRes = await db.collection('activities').doc(activityId).get();
        const activity = activityRes.data;
        if (!activity) {
            await transaction.rollback();
            throw err('NOT_FOUND', '活动不存在');
        }
        if (activity.maxParticipants && (activity.currentParticipants || 0) >= activity.maxParticipants) {
            await transaction.rollback();
            throw err('BUSINESS_ERROR', '报名人数已满');
        }
        const existReg = await db.collection('activity_registrations')
            .where({ activityId, openid, status: 'confirmed' })
            .count();
        if (existReg.total > 0) {
            await transaction.rollback();
            throw err('BUSINESS_ERROR', '您已报名此活动');
        }
        const pricePerPerson = activity.pricePerPerson || 0;
        const pricePerPet = activity.pricePerPet || 0;
        const pCount = participantCount || 1;
        const petsArray = pets;
        const friendsArray = Array.isArray(friends) ? friends : [];
        const petCount = petsArray.length + friendsArray.length;
        const calculatedAmount = pricePerPerson * pCount + pricePerPet * petCount;
        // 仅在使用优惠券时，校验优惠后金额下限（直接使用前端传入的已扣券金额）
        if (couponId && Number(totalAmount) > 0 && Number(totalAmount) < 0.1) {
            throw err('INVALID_PARAMS', '优惠后订单金额必须 ≥ 0.1 元');
        }
        // Sprint 22: 活动报名前先做大额风控
        const applyRisk = await performActivityApplyRiskCheck({
            openid,
            activityId,
            amountFen: Math.round(calculatedAmount * 100),
        });
        const isPaid = calculatedAmount > 0;
        const now = db.serverDate();
        const petsInfo = petsArray.map((p) => ({
            name: p.petName || p.name || '',
            gender: p.petGender || p.gender || 'male',
            breed: p.petBreed || p.breed || '',
            petId: p.petId || '',
        }));
        const registration = {
            _id: generateId('registration', openid),
            activityId,
            ownerId: openid,
            pets: petsInfo,
            petIds: petIds || [],
            phone: phone || '',
            notes: notes || '',
            friends: friendsArray,
            // 活动报名状态语义：
            //   pending_payment: 待支付
            //   confirmed: 报名成功且支付完成
            //   cancelled: 已取消报名
            //   refunded: 已退款
            status: isPaid ? 'pending_payment' : 'confirmed',
            participantCount: pCount,
            petCount,
            pricePerPerson,
            pricePerPet,
            totalAmount: calculatedAmount,
            originalAmount: originalAmount || calculatedAmount,
            couponId: couponId || '',
            couponDiscount: couponDiscount || 0,
            finalAmount: totalAmount,
            pendingReview: applyRisk.pendingReview,
            riskDecision: applyRisk.decision,
            riskReasons: applyRisk.reasons,
            createdAt: now,
            updatedAt: now,
        };
        const regResult = await transaction.collection('activity_registrations').add({ data: registration });
        if (!isPaid) {
            await transaction.collection('activities').doc(activityId).update({
                data: {
                    currentParticipants: _.inc(pCount),
                    updatedAt: db.serverDate(),
                },
            });
        }
        try {
            let user = null;
            try {
                const userRes = await db.collection('users').doc(openid).get();
                user = userRes.data;
            }
            catch (e) {
                logger.warn('submitRegistration.users.fetch', { openid, code: e.errCode, msg: e.message });
            }
            const activityOrder = {
                ownerId: openid,
                orderType: 'activity',
                activityId,
                activityTitle: activity.title || '',
                activityCoverUrl: activity.coverUrl || '',
                activityStartTime: activity.startTime || '',
                activityEndTime: activity.endTime || '',
                activityLocation: activity.location || '',
                organizerId: activity.createdBy || '',
                petIds: petIds || [],
                petsInfo,
                startDate: activity.startTime || '',
                endDate: activity.endTime || '',
                duration: 1,
                pricePerDay: activity.price || 0,
                participantCount: pCount,
                petCount,
                pricePerPerson,
                pricePerPet,
                basicPrice: calculatedAmount,
                totalPrice: totalAmount || calculatedAmount,
                originalAmount: originalAmount || calculatedAmount,
                couponId: couponId || '',
                couponDiscount: couponDiscount || 0,
                phone: phone || '',
                notes: notes || '',
                status: isPaid ? 'pending_payment' : 'confirmed',
                ownerInfo: user ? { nickName: user.nickName, avatarUrl: user.avatarUrl, phone } : { phone },
                createdAt: now,
                updatedAt: now,
            };
            await transaction.collection('orders').add({ data: activityOrder });
        }
        catch (orderErr) {
            logger.warn('创建活动订单记录失败:', orderErr.message);
        }
        await transaction.commit();
        return handleSuccess({ id: regResult._id || 'ok', registrationId: regResult._id }, '报名成功');
    }
    catch (error) {
        await transaction.rollback();
        return handleError(error, '报名失败', ERROR_CODES.DATA);
    }
}
exports.submitRegistration = submitRegistration;
// =====================================================================
// Handler 7: getRegistrationDetail - 报名详情
// =====================================================================
async function getRegistrationDetail(event, context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { registrationId } = event;
    if (!registrationId) {
        throw err('INVALID_PARAMS', '缺少订单ID');
    }
    try {
        let registration = null;
        try {
            const regRes = await db.collection('activity_registrations').doc(registrationId).get();
            if (regRes.data && regRes.data.ownerId === openid) {
                registration = regRes.data;
            }
        }
        catch (e) {
            logger.warn('getRegistrationDetail.activity_registrations.fetch', { registrationId, code: e.errCode, msg: e.message });
        }
        if (!registration) {
            try {
                const orderRes = await db.collection('orders').doc(registrationId).get();
                if (orderRes.data) {
                    const order = orderRes.data;
                    if (order.ownerId === openid) {
                        const regQuery = await db.collection('activity_registrations')
                            .where({ activityId: order.activityId, ownerId: openid })
                            .limit(1).get();
                        const regData = (regQuery.data || []);
                        if (regData.length > 0) {
                            registration = regData[0];
                        }
                        else {
                            registration = {
                                _id: order._id,
                                activityId: order.activityId || '',
                                ownerId: openid,
                                pets: order.petsInfo || [],
                                phone: order.phone || '',
                                notes: order.notes || '',
                                participantCount: order.participantCount || 1,
                                petCount: order.petCount || 0,
                                totalAmount: order.totalPrice || order.basicPrice || 0,
                                originalAmount: order.originalAmount || order.totalPrice || 0,
                                couponId: order.couponId || '',
                                couponDiscount: order.couponDiscount || 0,
                                finalAmount: order.totalPrice || 0,
                                status: order.status || 'pending',
                                createdAt: order.createdAt,
                            };
                        }
                    }
                    else {
                        throw err('AUTH_REQUIRED', '无权查看此订单');
                    }
                }
            }
            catch (e) {
                logger.warn('getRegistrationDetail.orders.lookup', { registrationId, code: e.errCode, msg: e.message });
            }
        }
        if (!registration) {
            throw err('NOT_FOUND', '订单不存在');
        }
        let activityInfo = null;
        try {
            const activityRes = await db.collection('activities').doc(registration.activityId).get();
            if (activityRes.data) {
                const act = activityRes.data;
                activityInfo = {
                    title: act.title || '',
                    coverUrl: act.coverUrl || '',
                    startTime: act.startTime || '',
                    endTime: act.endTime || '',
                    location: act.location || '',
                    pricePerPerson: act.pricePerPerson || 0,
                    pricePerPet: act.pricePerPet || 0,
                };
            }
        }
        catch (e) {
            logger.warn('getRegistrationDetail: 获取活动信息失败', e.message);
        }
        return handleSuccess({
            registration,
            activityInfo,
        }, '获取成功');
    }
    catch (error) {
        logger.error('getRegistrationDetail', error);
        return handleError(error, '获取报名详情失败', ERROR_CODES.BUSINESS);
    }
}
exports.getRegistrationDetail = getRegistrationDetail;
// =====================================================================
// Handler 8: getRegistrationList - 报名列表
// =====================================================================
async function getRegistrationList(event, context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { page = 1, pageSize = 20, activityId, status } = event;
    const where = { openid };
    if (activityId) {
        where.activityId = activityId;
    }
    if (status) {
        where.status = status;
    }
    const result = await paginate(db, 'activity_registrations', {
        page, pageSize: Math.min(pageSize, 20), where, projection: REGISTRATION_LIST_FIELDS,
        orderBy: { field: 'createdAt', direction: 'desc' },
    });
    const activityIds = [...new Set(result.list.map((r) => r.activityId).filter((id) => Boolean(id)))];
    if (activityIds.length > 0) {
        const activitiesRes = await db.collection('activities')
            .where({ _id: _.in(activityIds) })
            .get();
        const activityMap = {};
        (activitiesRes.data || []).forEach((a) => { if (a._id) {
            activityMap[a._id] = a;
        } });
        const regMap = {};
        result.list.forEach((r) => { if (r.activityId) {
            regMap[r.activityId] = r;
        } });
        let activities = activityIds
            .map((id) => activityMap[id])
            .filter((a) => Boolean(a))
            .map((a) => {
            const reg = regMap[a._id || ''];
            return {
                ...a,
                joined: true,
                _registrationId: reg ? (reg._id || '') : (a._id || ''),
                regStatus: reg ? reg.status : '',
                regCreatedAt: reg ? reg.createdAt : a.createdAt,
            };
        });
        if (status === 'active') {
            const now = new Date();
            const utc = now.getTime() + (now.getTimezoneOffset() * 60000);
            const bjTime = new Date(utc + (8 * 3600000));
            const nowStr = `${bjTime.getFullYear()}-${String(bjTime.getMonth() + 1).padStart(2, '0')}-${String(bjTime.getDate()).padStart(2, '0')} ${String(bjTime.getHours()).padStart(2, '0')}:${String(bjTime.getMinutes()).padStart(2, '0')}`;
            activities = activities.filter((a) => {
                if (a.status === 'ended' || a.status === 'cancelled' || a.status === 'deleted') {
                    return false;
                }
                if (a.endTime) {
                    const end = new Date(String(a.endTime).replace(/-/g, '/'));
                    if (!isNaN(end.getTime()) && end <= now) {
                        return false;
                    }
                }
                return true;
            });
            result.total = activities.length;
        }
        const invalidAvatarList = [];
        for (const activity of activities) {
            if (activity.organizer && activity.organizer.avatar) {
                const avatar = activity.organizer.avatar;
                if (!avatar.startsWith('cloud://') && !avatar.startsWith('https://')) {
                    activity.organizer.avatar = '';
                    if (activity.createdBy) {
                        invalidAvatarList.push(activity);
                    }
                }
            }
        }
        if (invalidAvatarList.length > 0) {
            const creatorOpenids = [...new Set(invalidAvatarList.map((a) => a.createdBy).filter((id) => Boolean(id)))];
            try {
                const adminRes = await db.collection('admins').where({ _id: _.in(creatorOpenids) }).field({ avatarUrl: true, nickName: true }).get();
                const adminMap = {};
                (adminRes.data || []).forEach((a) => { if (a._id) {
                    adminMap[a._id] = a;
                } });
                invalidAvatarList.forEach((activity) => {
                    if (!activity.createdBy || !activity.organizer) {
                        return;
                    }
                    const admin = adminMap[activity.createdBy];
                    if (admin && admin.avatarUrl && (admin.avatarUrl.startsWith('cloud://') || admin.avatarUrl.startsWith('https://'))) {
                        activity.organizer.avatar = admin.avatarUrl;
                        if (admin.nickName && activity.organizer.name === '宠团团') {
                            activity.organizer.name = admin.nickName;
                        }
                    }
                });
            }
            catch (e) {
                logger.warn('getRegistrationList.admins.fetch', { count: creatorOpenids.length, code: e.errCode, msg: e.message });
            }
        }
        result.list = activities;
    }
    else {
        result.list = [];
    }
    return handleSuccess(result, '获取成功');
}
exports.getRegistrationList = getRegistrationList;
// =====================================================================
// Handler 9: createActivityPaymentOrder - 创建活动支付订单
// =====================================================================
async function createActivityPaymentOrder(event, context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { activityId, pets, phone, notes, friends, petIds, totalAmount, originalAmount, couponId, couponDiscount, orderId } = event;
    if (!activityId) {
        throw err('INVALID_PARAMS', '缺少活动ID');
    }
    if (!pets || !Array.isArray(pets) || pets.length === 0) {
        throw err('INVALID_PARAMS', '请选择参与的宠物');
    }
    if (!phone) {
        throw err('INVALID_PARAMS', '请填写联系电话');
    }
    if (!totalAmount || totalAmount <= 0) {
        throw err('INVALID_PARAMS', '金额异常');
    }
    try {
        const activityRes = await db.collection('activities').doc(activityId).get();
        const activity = activityRes.data;
        if (!activity) {
            throw err('NOT_FOUND', '活动不存在');
        }
        if (activity.maxParticipants && (activity.currentParticipants || 0) >= activity.maxParticipants) {
            throw err('BUSINESS_ERROR', '报名人数已满');
        }
        const existReg = await db.collection('activity_registrations')
            .where({ activityId, ownerId: openid, status: _.in(['confirmed', 'pending_payment']) })
            .count();
        if (existReg.total > 0) {
            throw err('BUSINESS_ERROR', '您已报名此活动');
        }
        const now = db.serverDate();
        const petsArray = pets;
        const petsInfo = petsArray.map((p) => ({
            name: p.petName || p.name || '',
            gender: p.petGender || p.gender || 'male',
            breed: p.petBreed || p.breed || '',
            petId: p.petId || '',
        }));
        const pendingRegistration = {
            _id: generateId('registration', openid),
            activityId,
            ownerId: openid,
            orderId,
            pets: petsInfo,
            petIds: petIds || [],
            phone: phone || '',
            notes: notes || '',
            friends: Array.isArray(friends) ? friends : [],
            status: 'pending_payment',
            totalAmount,
            originalAmount: originalAmount || totalAmount,
            couponId: couponId || '',
            couponDiscount: couponDiscount || 0,
            finalAmount: totalAmount,
            createdAt: now,
            updatedAt: now,
        };
        const regResult = await db.collection('activity_registrations').add({ data: pendingRegistration });
        const orderDoc = {
            ownerId: openid,
            orderType: 'activity',
            orderId,
            activityId,
            activityTitle: activity.title || '',
            activityCoverUrl: activity.coverUrl || '',
            activityStartTime: activity.startTime || '',
            activityEndTime: activity.endTime || '',
            activityLocation: activity.location || '',
            organizerId: activity.createdBy || '',
            petIds: petIds || [],
            petsInfo,
            startDate: activity.startTime || '',
            endDate: activity.endTime || '',
            duration: 1,
            pricePerDay: activity.price || 0,
            petCount: petsArray.length,
            basicPrice: totalAmount,
            totalPrice: totalAmount,
            originalAmount: originalAmount || totalAmount,
            couponId: couponId || '',
            couponDiscount: couponDiscount || 0,
            phone: phone || '',
            notes: notes || '',
            status: 'pending_payment',
            paymentStatus: 'pending',
            createdAt: now,
            updatedAt: now,
        };
        await db.collection('orders').add({ data: orderDoc });
        const paymentParams = await _createPaymentParams(openid, orderId || '', totalAmount, activity.title || '活动报名');
        return handleSuccess({
            orderId,
            registrationId: regResult._id,
            paymentParams,
        }, '订单创建成功');
    }
    catch (error) {
        return handleError(error, '创建订单失败', ERROR_CODES.DATA);
    }
}
exports.createActivityPaymentOrder = createActivityPaymentOrder;
// =====================================================================
// Handler 10: confirmActivityPayment - 确认活动支付
// =====================================================================
async function confirmActivityPayment(event, context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { orderId } = event;
    if (!orderId) {
        throw err('INVALID_PARAMS', '缺少订单ID');
    }
    const transaction = await db.startTransaction();
    try {
        const orderRes = await db.collection('orders').where({ orderId, ownerId: openid }).get();
        const orderList = (orderRes.data || []);
        if (orderList.length === 0) {
            await transaction.rollback();
            throw err('NOT_FOUND', '订单不存在');
        }
        const order = orderList[0];
        if (order.status !== 'pending_payment') {
            await transaction.rollback();
            throw err('BUSINESS_ERROR', '订单状态异常');
        }
        const now = db.serverDate();
        await transaction.collection('orders').doc(order._id || '').update({
            data: { status: 'confirmed', paymentStatus: 'paid', paidAt: now, updatedAt: now },
        });
        await transaction.collection('activity_registrations')
            .where({ orderId, openid, status: 'pending_payment' })
            .update({
            data: { status: 'confirmed', updatedAt: now },
        });
        await transaction.collection('activities').doc(order.activityId || '').update({
            data: {
                currentParticipants: _.inc(order.petCount || 1),
                updatedAt: now,
            },
        });
        await transaction.commit();
        // 活动佣金在活动结束时生成，不在支付时生成
        // 佣金由 autoUpdateActivityStatus 在活动时间到达 endTime 时触发
        return handleSuccess({ orderId }, '支付成功');
    }
    catch (error) {
        await transaction.rollback();
        return handleError(error, '支付确认失败', ERROR_CODES.DATA);
    }
}
exports.confirmActivityPayment = confirmActivityPayment;
// =====================================================================
// Handler 14: cancelRegistration - 用户取消活动报名
// =====================================================================
async function cancelRegistration(event, context, auth) {
  const { openid } = auth;
  if (!openid) {
    throw err('AUTH_REQUIRED', '未登录');
  }
  const { registrationId } = event;
  if (!registrationId) {
    throw err('INVALID_PARAMS', '缺少报名ID');
  }

  const regRes = await db.collection('activity_registrations').doc(registrationId).get();
  if (!regRes.data) {
    throw err('NOT_FOUND', '报名记录不存在');
  }
  const reg = regRes.data;
  if (reg.ownerId !== openid) {
    throw err('PERMISSION_DENIED', '无权操作');
  }
  if (!['confirmed', 'pending_payment'].includes(reg.status)) {
    throw err('BUSINESS_ERROR', '当前状态不可取消');
  }

  const now = db.serverDate();

  // 1. 取消佣金（已结束时可能已经生成佣金）
  if (reg.orderId) {
    try {
      await cancelCommissionRecord(reg.orderId);
      logger.info('cancelRegistration.cancelCommissionRecord.success', { registrationId, orderId: reg.orderId });
    } catch (e) {
      logger.warn('cancelRegistration.cancelCommissionRecord.failed', { registrationId, orderId: reg.orderId, msg: e.message });
    }
  }

  // 2. 取消收入
  if (reg.orderId) {
    try {
      const { cancelServiceIncomeRecord } = require('./common/service-income-utils');
      await cancelServiceIncomeRecord(reg.orderId, 'activity');
      logger.info('cancelRegistration.cancelServiceIncomeRecord.success', { registrationId, orderId: reg.orderId });
    } catch (e) {
      logger.warn('cancelRegistration.cancelServiceIncomeRecord.failed', { registrationId, orderId: reg.orderId, msg: e.message });
    }
  }

  // 3. 调用微信支付退款（已支付/confirmed 状态）
  if (reg.status === 'confirmed' && reg.orderId) {
    try {
      const finalAmount = Math.round(Number(reg.finalAmount || reg.totalAmount || 0) * 100);
      if (finalAmount > 0) {
        await cloud.callFunction({
          name: 'paymentService',
          data: {
            action: 'createRefund',
            outTradeNo: reg.orderId,
            refundAmount: finalAmount,
            totalAmount: Math.round(Number(reg.totalAmount || reg.finalAmount || 0) * 100),
          },
        });
        logger.info('cancelRegistration.refundCreated', { registrationId, orderId: reg.orderId });
      }
    } catch (e) {
      logger.warn('cancelRegistration.refundFailed', { registrationId, orderId: reg.orderId, msg: e.message });
    }
  }

  // 4. 更新 activity_registrations 状态
  await db.collection('activity_registrations').doc(registrationId).update({
    data: { status: 'cancelled', updatedAt: now },
  });

  // 5. 同步 orders 统一表状态
  if (reg.orderId) {
    try {
      await db.collection('orders').where({ orderId: reg.orderId, ownerId: openid }).update({
        data: { status: 'cancelled', updatedAt: now },
      });
    } catch (e) {
      logger.warn('cancelRegistration.syncOrderFailed', { registrationId, orderId: reg.orderId, msg: e.message });
    }
  }

  // 6. 恢复活动名额
  if (reg.activityId) {
    try {
      await db.collection('activities').doc(reg.activityId).update({
        data: { currentParticipants: _.inc(-(reg.petCount || 1)), updatedAt: now },
      });
    } catch (e) {
      logger.warn('cancelRegistration.restoreParticipantsFailed', { registrationId, activityId: reg.activityId, msg: e.message });
    }
  }

  return handleSuccess(null, '取消成功');
}
exports.cancelRegistration = cancelRegistration;
// =====================================================================
// Handler 11: getActivityRegistrations - 活动报名列表（合作伙伴）
// =====================================================================
async function getActivityRegistrations(event, context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { activityId, page = 1, pageSize = 20 } = event;
    if (!activityId) {
        throw err('INVALID_PARAMS', '缺少活动ID');
    }
    await checkPartnerPermission(openid, 'activity');
    const safePageSize = Math.min(Math.max(1, Number(pageSize) || 20), 100);
    const result = await paginate(db, 'activity_registrations', {
        page, pageSize: safePageSize,
        where: { activityId },
        orderBy: { field: 'createdAt', direction: 'desc' },
    });
    if (result.list && result.list.length > 0) {
        const openids = result.list.map((r) => r.ownerId).filter((id) => Boolean(id));
        if (openids.length > 0) {
            const usersRes = await db.collection('users').where({ _id: _.in(openids) }).get();
            const userMap = {};
            (usersRes.data || []).forEach((u) => { if (u._id) {
                userMap[u._id] = u;
            } });
            result.list = result.list.map((r) => {
                const user = userMap[r.ownerId || ''] || {};
                return {
                    ...r,
                    userNickName: user.nickName || '',
                    userAvatar: user.avatarUrl || '',
                    displayName: user.nickName || '未知用户',
                };
            });
        }
        else {
            result.list = result.list.map((r) => ({
                ...r,
                userNickName: '',
                userAvatar: '',
                displayName: '未知用户',
            }));
        }
    }
    return handleSuccess(result, '获取成功');
}
exports.getActivityRegistrations = getActivityRegistrations;
// =====================================================================
// Handler 12: exportActivityRegistrations - 导出活动报名（CSV）
// =====================================================================
async function exportActivityRegistrations(event, context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { activityId } = event;
    if (!activityId) {
        throw err('INVALID_PARAMS', '缺少活动ID');
    }
    await checkPartnerPermission(openid, 'activity');
    const activityRes = await db.collection('activities').doc(activityId).get();
    const activity = activityRes.data;
    if (!activity) {
        throw err('NOT_FOUND', '活动不存在');
    }
    const registrationsRes = await db.collection('activity_registrations')
        .where({ activityId })
        .orderBy('createdAt', 'desc')
        .get();
    let registrations = (registrationsRes.data || []);
    if (registrations.length > 0) {
        const openids = registrations.map((r) => r.ownerId).filter((id) => Boolean(id));
        if (openids.length > 0) {
            const usersRes = await db.collection('users').where({ _id: _.in(openids) }).get();
            const userMap = {};
            (usersRes.data || []).forEach((u) => { if (u._id) {
                userMap[u._id] = u;
            } });
            registrations = registrations.map((r) => ({
                ...r,
                userNickName: (r.ownerId && userMap[r.ownerId]?.nickName) || '',
            }));
        }
    }
    const headers = ['序号', '宠物昵称', '报名时间', '用户昵称', '联系电话', '备注', '签到'];
    const rows = registrations.map((reg, index) => [
        index + 1,
        (reg.pets && reg.pets.map((p) => p.name).join(', ')) || '',
        reg.createdAt ? new Date(reg.createdAt).toLocaleString('zh-CN') : '',
        reg.userNickName || '',
        reg.phone || '',
        reg.notes || '',
        '',
    ]);
    const csvContent = [headers.join(','), ...rows.map((row) => row.map((cell) => {
            const str = String(cell).replace(/"/g, '""');
            return `"${str}"`;
        }).join(','))].join('\n');
    const exportResult = {
        activityTitle: activity.title || '',
        totalCount: registrations.length,
        csvContent,
    };
    return handleSuccess(exportResult, '导出成功');
}
exports.exportActivityRegistrations = exportActivityRegistrations;
// =====================================================================
// Handler 13: getActivityOrders - 活动订单列表（合作伙伴）
// =====================================================================
async function getActivityOrders(event, context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    await checkPartnerPermission(openid, 'activity');
    const { status, page = 1, pageSize = 20 } = event;
    const safePageSize = Math.min(Math.max(1, Number(pageSize) || 20), 100);
    const where = { orderType: 'activity' };
    if (status) {
        where.status = status;
    }
    const result = await paginate(db, 'orders', {
        page, pageSize: safePageSize,
        where,
        orderBy: { field: 'createdAt', direction: 'desc' },
    });
    const list = (result.list || []);
    const enrichedList = list.map((order) => ({
        ...order,
        buyerNickName: order.ownerInfo?.nickName || '',
        productName: order.activityTitle || '',
    }));
    return handleSuccess({ ...result, list: enrichedList }, '获取成功');
}
exports.getActivityOrders = getActivityOrders;
// =====================================================================
// 入口聚合：handlers 路由表
// =====================================================================
exports.handlers = {
    getActivityList,
    getActivityDetail,
    createActivity,
    updateActivity,
    deleteActivity,
    submitRegistration,
    getRegistrationDetail,
    getRegistrationList,
    createActivityPaymentOrder,
    confirmActivityPayment,
    cancelRegistration,
    getActivityRegistrations,
    exportActivityRegistrations,
    getActivityOrders,
};
// =====================================================================
// Main 入口（云函数调用）
// =====================================================================
async function main(event, context) {
    const { action } = event;
    if (!action || !exports.handlers[action]) {
        throw err('INVALID_PARAMS', '无效的操作类型');
    }
    const WRITE_ACTIONS = ['createActivity', 'updateActivity', 'deleteActivity', 'submitRegistration', 'createActivityPaymentOrder', 'confirmActivityPayment', 'cancelRegistration'];
    const LOGIN_REQUIRED_ACTIONS = [...WRITE_ACTIONS, 'getActivityDetail', 'getRegistrationDetail', 'getRegistrationList', 'getActivityRegistrations', 'exportActivityRegistrations', 'getActivityOrders', 'cancelRegistration'];
    const requireLogin = LOGIN_REQUIRED_ACTIONS.includes(action);
    try {
        const auth = await verifyAuth(event, { requireLogin });
        logger.info(action, { openid: auth.openid });
        return await exports.handlers[action](event, context, auth);
    }
    catch (error) {
        logger.error(action, error);
        const code = error.code || ERROR_CODES.BUSINESS;
        return handleError(error, error.message, code);
    }
}
exports.main = main;
// =====================================================================
// Runtime shim: CommonJS 兼容
// =====================================================================
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const _mod = module;
_mod.exports = {
    main,
    getActivityList,
    getActivityDetail,
    createActivity,
    updateActivity,
    deleteActivity,
    submitRegistration,
    getRegistrationDetail,
    getRegistrationList,
    createActivityPaymentOrder,
    confirmActivityPayment,
    getActivityRegistrations,
    exportActivityRegistrations,
    getActivityOrders,
    handlers: exports.handlers,
};
_mod.exports.default = _mod.exports;
exports.default = {
    main,
    getActivityList,
    getActivityDetail,
    createActivity,
    updateActivity,
    deleteActivity,
    submitRegistration,
    getRegistrationDetail,
    getRegistrationList,
    createActivityPaymentOrder,
    confirmActivityPayment,
    getActivityRegistrations,
    exportActivityRegistrations,
    getActivityOrders,
    handlers: exports.handlers,
};
