/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
"use strict";
/**
 * paymentService/index.ts - 支付服务统一入口（TypeScript 源文件 - Sprint 47 迁移）
 *
 * 业务功能（聚合 pay / refund / notify 三个 service）：
 *   - pay     子服务：createPayment / queryPayment / closePayment / confirmPayment
 *   - refund  子服务：createRefund / queryRefund
 *   - notify  子服务：paymentNotify（微信支付 V3 HTTP 回调）
 *
 * 入口分发：
 *   - HTTP 请求（微信支付回调）：event.headers + event.body + !event.action
 *     → 直接调用 paymentNotify，跳过鉴权
 *   - 普通 API 请求：按 event.action 分发到对应 handler
 *     → 调用 verifyAuth 鉴权（paymentNotify 之外都需要登录）
 *
 * 关键设计：
 *   - 鉴权：paymentNotify 不需要登录（在 NO_AUTH_ACTIONS 中声明）
 *   - 错误：err() 工厂 + toResponse 统一响应
 *   - 业务错误：isBusinessError 类型守卫替代裸字符串 e.code === 'X'
 *   - 限流：Sprint 21 注入 initGlobalRateLimitFromDb（基于 db.rate_limits 共享计数）
 *
 * 迁移目标：
 *   - 强类型化 6 个 handler + 1 个 notify 入口
 *   - 强类型化 CloudEvent / CloudContext / AuthLike（与已迁移的 12 个服务对齐）
 *   - 抽离 NO_AUTH_ACTIONS 常量 + CloudEvent 事件分支判定
 *   - 编译产物（index.js）继续被云函数 runtime require
 *
 * 编译方式：
 *   npx --yes -p typescript@5.4.5 tsc -p tsconfig.paymentService.json
 *   （运行时仍消费 .js 编译产物）
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.main = exports.handlers = exports.isHttpRequest = exports.SUPPORTED_ACTIONS = exports.NO_AUTH_ACTIONS = void 0;
// Sprint 47 迁移说明：
//   - 仍消费 .js 编译产物（tsc 输出到 cloudfunctions/paymentService/index.js）
//   - 对 .js 文件（utils / errors / logger / auth-middleware / risk-rate-limit）使用 require() 而非 import
//   - 强类型作用于 common/* 与本文件内部接口
//   - 不直接依赖子服务的内部 .ts（依赖 .js 编译产物，避免 tsconfig include 串扰）
const utils_1 = require("./common/utils");
const logger_1 = require("./common/logger");
const errors_1 = require("./common/errors");
// service 内部 .js 模块走 CommonJS require
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { verifyAuth } = require('./common/auth-middleware');
// Sprint 50: 限流统一 bootstrap
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { bootstrapRateLimit } = require('./common/rate-limit-bootstrap');
// =====================================================================
// 常量
// =====================================================================
/** 不需要登录的 actions（HTTP 回调或公开 endpoint） */
exports.NO_AUTH_ACTIONS = ['paymentNotify'];
/** 支持的 action 集合（用于 fail-fast 校验） */
exports.SUPPORTED_ACTIONS = [
    // pay 子服务
    'createPayment',
    'queryPayment',
    'closePayment',
    'confirmPayment',
    // refund 子服务
    'createRefund',
    'queryRefund',
    // notify 子服务（HTTP 回调走 isHttpRequest 分支）
    'paymentNotify',
];
// =====================================================================
// 模块初始化
// =====================================================================
const logger = (0, logger_1.createLogger)('paymentService');
// =====================================================================
// 工具函数
// =====================================================================
/** 判定 event 是否为 HTTP 触发（微信支付回调入口） */
function isHttpRequest(event) {
    return Boolean(event.headers) && event.body !== undefined && !event.action;
}
exports.isHttpRequest = isHttpRequest;
// =====================================================================
// 子服务 handlers 聚合
// =====================================================================
// eslint-disable-next-line @typescript-eslint/no-var-requires
const payHandlers = require('./services/pay');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const refundHandlers = require('./services/refund');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const notifyHandlers = require('./services/notify');
/** 聚合后的 handlers（所有子服务暴露的 action） */
exports.handlers = {
    ...payHandlers,
    ...refundHandlers,
    ...notifyHandlers,
};
// =====================================================================
// Sprint 50: 限流统一 bootstrap（rate_limits + rate_limit_configs 一次注入）
//   - 跨云函数实例共享计数 + 业务类型差异化配置（payment/refund 走更严阈值）
//   - 若 db 不可用则降级到内存
// =====================================================================
try {
    const { db } = (0, utils_1.initCloud)();
    bootstrapRateLimit(db, {
        logger: (0, logger_1.createLogger)('paymentService.rate-limit'),
    });
}
catch (e) {
    logger.warn('bootstrapRateLimit failed, fallback to memory', { error: e?.message });
}
// =====================================================================
// Main 入口
// =====================================================================
/**
 * 支付服务统一入口
 *
 * 流程：
 *   1. 若 event 是 HTTP 请求（微信支付回调）→ 直接调 paymentNotify
 *   2. 否则按 event.action 分发到对应 handler
 *   3. 对需要登录的 action 调 verifyAuth 注入 auth
 *   4. 错误统一走 handleError / toResponse 序列化
 *
 * @throws BusinessError UNKNOWN_ACTION（未知 action）
 */
async function main(event, context) {
    // HTTP 触发（微信支付回调）走特殊分支
    if (isHttpRequest(event)) {
        return await exports.handlers.paymentNotify(event, context, null);
    }
    const { action } = event;
    if (!action) {
        throw (0, errors_1.err)('UNKNOWN_ACTION', '缺少 action 参数');
    }
    if (!exports.handlers[action]) {
        throw (0, errors_1.err)('UNKNOWN_ACTION', `未知的操作：${action}`);
    }
    try {
        const requireLogin = !exports.NO_AUTH_ACTIONS.includes(action);
        const auth = await verifyAuth(event, { requireLogin });
        logger.info(action, { openid: auth.openid });
        return await exports.handlers[action](event, context, auth);
    }
    catch (error) {
        logger.error(action, error);
        if ((0, errors_1.isBusinessError)(error)) {
            return (0, errors_1.toResponse)(error);
        }
        const code = Number(error.code) || utils_1.ERROR_CODES.BUSINESS;
        return (0, utils_1.handleError)(error, error.message || '操作失败', code);
    }
}
exports.main = main;
// =====================================================================
// Runtime shim（CommonJS 兼容）
// =====================================================================
const _mod = module;
_mod.exports = {
    main,
    // 常量
    NO_AUTH_ACTIONS: exports.NO_AUTH_ACTIONS,
    SUPPORTED_ACTIONS: exports.SUPPORTED_ACTIONS,
    // 工具函数
    isHttpRequest,
    // 聚合 handlers（用于单元测试）
    handlers: exports.handlers,
};
_mod.exports.default = _mod.exports;
exports.default = {
    main,
    NO_AUTH_ACTIONS: exports.NO_AUTH_ACTIONS,
    SUPPORTED_ACTIONS: exports.SUPPORTED_ACTIONS,
    isHttpRequest,
    handlers: exports.handlers,
};
