/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
"use strict";
/**
 * petService/index.ts - 宠物服务主入口（TypeScript 源文件 - Sprint 44 迁移）
 *
 * 业务功能：
 *   - 宠物档案 CRUD（创建 / 更新 / 删除）
 *   - 宠物查询（列表 / 详情 / 单条）
 *   - 软删除（isActive=0 标记）
 *   - 缓存层（pets_${openid} / pet_${petId}）
 *
 * 共 6 个 action：
 *   1. createPet - 创建宠物档案
 *   2. updatePet - 更新宠物档案
 *   3. deletePet - 删除宠物（软删除）
 *   4. getPet - 获取宠物（公开）
 *   5. getPetList - 我的宠物列表
 *   6. getPetDetail - 宠物详情（公开）
 *
 * 验证规则：
 *   - VALID_TYPES: ['cat', 'dog', 'exotic']
 *   - VALID_GENDERS: ['male', 'female', 'unknown']
 *
 * 迁移目标：
 *   - 强类型化所有 db 操作、handler 签名、返回结构
 *   - 复用 AuthLike / CloudEvent / CloudContext 公共类型
 *   - 宠物类型 / 性别 / 字段强类型化
 *   - 与 adminService / partnerService / userService / activityService / mallService / feedingService / hostService / couponService 保持类型一致
 *
 * 编译方式：
 *   npx --yes -p typescript@5.4.5 tsc -p tsconfig.petService.json
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.main = exports.handlers = exports.getPet = exports.getPetDetail = exports.getPetList = exports.deletePet = exports.updatePet = exports.createPet = exports.convertWeight = void 0;
// =====================================================================
// 内部模块初始化（require CommonJS 模块）
// =====================================================================
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { err } = require('./common/errors');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { initCloud, handleSuccess, handleError, generateId, ERROR_CODES } = require('./common/utils');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createLogger } = require('./common/logger');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { verifyAuth } = require('./common/auth-middleware');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { getCache, setCache, deleteCache } = require('./common/cache');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { filterFields, FIELD_WHITELISTS } = require('./common/validator');
const { cloud, db } = initCloud();
const logger = createLogger('petService');
const _ = db.command;
// =====================================================================
// 验证常量
// =====================================================================
const VALID_TYPES = ['cat', 'dog', 'exotic'];
const VALID_GENDERS = ['male', 'female', 'unknown'];
const PET_FIELDS = {
    _id: true, name: true, type: true, breed: true, gender: true,
    birthday: true, weight: true, avatarUrl: true, note: true,
    createdAt: true, updatedAt: true,
};
const PET_DETAIL_FIELDS = {
    _id: true, name: true, type: true, breed: true, gender: true,
    birthday: true, weight: true, avatarUrl: true, note: true,
    ownerId: true, _openid: true, isActive: true,
    createdAt: true, updatedAt: true,
};
// =====================================================================
// 辅助函数：体重转换
// =====================================================================
function convertWeight(weight) {
    if (weight === undefined || weight === null || weight === '') {
        return null;
    }
    const num = Number(weight);
    return isNaN(num) || num <= 0 ? null : num;
}
exports.convertWeight = convertWeight;
// =====================================================================
// Handler 1: createPet
// =====================================================================
async function createPet(event, _context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { name, type, gender, breed, birthday, weight, note, avatarUrl } = event;
    logger.info('createPet 收到参数:', {
        name, type, gender, breed,
        hasBirthday: Boolean(birthday),
        hasWeight: Boolean(weight),
        hasNote: Boolean(note),
        hasAvatarUrl: Boolean(avatarUrl),
        eventKeys: Object.keys(event),
    });
    if (!name || !type || !breed || !gender) {
        logger.warn('createPet 必填校验失败:', {
            name: Boolean(name), type: Boolean(type), breed: Boolean(breed), gender: Boolean(gender),
        });
        throw err('INVALID_PARAMS', '请填写完整信息（昵称、类型、品种、性别）');
    }
    if (!VALID_TYPES.includes(type)) {
        throw err('INVALID_PARAMS', '宠物类型无效');
    }
    if (!VALID_GENDERS.includes(gender)) {
        throw err('INVALID_PARAMS', '性别无效');
    }
    const parsedWeight = convertWeight(weight);
    const petData = {
        _id: generateId('pet', openid),
        name: String(name).trim(),
        type: type,
        gender: gender,
        breed: String(breed).trim(),
        birthday: birthday || '',
        weight: parsedWeight,
        note: note || '',
        avatarUrl: avatarUrl || '',
        ownerId: openid,
        _openid: openid,
        createdAt: db.serverDate(),
        updatedAt: db.serverDate(),
        isActive: 1,
    };
    await db.collection('pets').add({ data: petData });
    deleteCache(`pets_${openid}`);
    if (!petData.avatarUrl) {
        petData.avatarUrl = '/images/default-pet.png';
    }
    const result = { id: petData._id || '', pet: petData };
    return handleSuccess(result, '创建成功');
}
exports.createPet = createPet;
// =====================================================================
// Handler 2: updatePet
// =====================================================================
async function updatePet(event, _context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { petId, updateData } = event;
    if (!petId) {
        throw err('INVALID_PARAMS', '宠物 ID 不能为空');
    }
    if (!updateData || Object.keys(updateData).length === 0) {
        throw err('INVALID_PARAMS', '没有需要更新的数据');
    }
    try {
        const petResult = await db.collection('pets').doc(petId).get();
        if (!petResult.data) {
            throw err('NOT_FOUND', '更新失败，宠物不存在或您没有权限');
        }
        const existingPet = petResult.data;
        if (existingPet.ownerId !== openid) {
            throw err('PERMISSION_DENIED', '更新失败，宠物不存在或您没有权限');
        }
        const updateFields = {
            updatedAt: db.serverDate(),
            ...filterFields(FIELD_WHITELISTS.pet, updateData),
        };
        if (updateFields.weight !== undefined) {
            updateFields.weight = convertWeight(updateFields.weight);
        }
        if (updateFields.type !== undefined && !VALID_TYPES.includes(updateFields.type)) {
            throw err('INVALID_PARAMS', '宠物类型无效');
        }
        if (updateFields.gender !== undefined && !VALID_GENDERS.includes(updateFields.gender)) {
            throw err('INVALID_PARAMS', '性别无效');
        }
        if (updateFields.name !== undefined) {
            updateFields.name = String(updateFields.name).trim();
        }
        if (updateFields.breed !== undefined) {
            updateFields.breed = String(updateFields.breed).trim();
        }
        const updateResult = await db.collection('pets').doc(petId).update({ data: updateFields });
        const updatedCount = updateResult?.stats?.updated ?? 0;
        if (updatedCount === 0) {
            throw err('BUSINESS_ERROR', '更新失败，宠物不存在或您没有权限');
        }
        const updatedPetResult = await db.collection('pets').doc(petId).get();
        const updatedPet = (updatedPetResult.data || {});
        deleteCache(`pets_${openid}`);
        deleteCache(`pet_${petId}`);
        const result = { pet: updatedPet };
        return handleSuccess(result, '更新成功');
    }
    catch (error) {
        return handleError(error, '更新失败，请稍后重试', ERROR_CODES.DATA);
    }
}
exports.updatePet = updatePet;
// =====================================================================
// Handler 3: deletePet（软删除）
// =====================================================================
async function deletePet(event, _context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { petId } = event;
    if (!petId) {
        throw err('INVALID_PARAMS', '宠物 ID 不能为空');
    }
    try {
        const deleteResult = await db.collection('pets').where({
            _id: petId,
            ownerId: openid,
        }).update({
            data: { isActive: 0, updatedAt: db.serverDate() },
        });
        if (!deleteResult || deleteResult.stats?.updated === 0) {
            throw err('NOT_FOUND', '删除失败，宠物不存在或您没有权限');
        }
        deleteCache(`pets_${openid}`);
        deleteCache(`pet_${petId}`);
        return handleSuccess(null, '删除成功');
    }
    catch (error) {
        return handleError(error, '删除失败，请稍后重试', ERROR_CODES.DATA);
    }
}
exports.deletePet = deletePet;
// =====================================================================
// Handler 4: getPetList
// =====================================================================
async function getPetList(event, _context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { page = 1, pageSize = 20 } = event;
    const safePageSize = Math.min(Math.max(1, Number(pageSize) || 20), 100);
    const skip = (page - 1) * safePageSize;
    try {
        const countResult = await db.collection('pets')
            .where({ ownerId: openid, isActive: 1 })
            .count();
        const result = await db.collection('pets')
            .field(PET_FIELDS)
            .where({ ownerId: openid, isActive: 1 })
            .orderBy('createdAt', 'desc')
            .skip(skip)
            .limit(safePageSize)
            .get();
        const processedPets = (result.data || []).map((pet) => {
            const processedPet = { ...pet };
            if (!pet.avatarUrl) {
                processedPet.avatarUrl = '/images/default-pet.png';
            }
            return processedPet;
        });
        return handleSuccess({
            list: processedPets,
            total: countResult.total,
            page,
            pageSize: safePageSize,
            totalPages: Math.ceil(countResult.total / safePageSize),
        }, '获取成功');
    }
    catch (error) {
        return handleError(error, '获取失败，请稍后重试', ERROR_CODES.DATA);
    }
}
exports.getPetList = getPetList;
// =====================================================================
// Handler 5: getPetDetail（公开）
// =====================================================================
async function getPetDetail(event, _context, _auth) {
    const { petId } = event;
    if (!petId) {
        throw err('INVALID_PARAMS', '宠物 ID 不能为空');
    }
    const cacheKey = `pet_${petId}`;
    const cachedPet = getCache(cacheKey);
    if (cachedPet) {
        return handleSuccess({ pet: cachedPet }, '获取成功');
    }
    try {
        const result = await db.collection('pets')
            .field(PET_DETAIL_FIELDS)
            .where({ _id: petId, isActive: 1 })
            .get();
        if (!result.data || result.data.length === 0) {
            throw err('NOT_FOUND', '宠物不存在');
        }
        const pet = (result.data[0] || {});
        const processedPet = { ...pet };
        if (!processedPet.avatarUrl) {
            processedPet.avatarUrl = '/images/default-pet.png';
        }
        setCache(cacheKey, processedPet);
        return handleSuccess({ pet: processedPet }, '获取成功');
    }
    catch (error) {
        return handleError(error, '获取失败，请稍后重试', ERROR_CODES.DATA);
    }
}
exports.getPetDetail = getPetDetail;
// =====================================================================
// Handler 6: getPet（公开）
// =====================================================================
async function getPet(event, _context, _auth) {
    const { petId } = event;
    if (!petId) {
        throw err('INVALID_PARAMS', '宠物 ID 不能为空');
    }
    try {
        const petResult = await db.collection('pets').where({
            _id: petId,
            isActive: 1,
        }).get();
        if (!petResult?.data || petResult.data.length === 0) {
            throw err('NOT_FOUND', '宠物不存在或您没有权限');
        }
        const petData = (petResult.data[0] || {});
        return handleSuccess({ pet: petData }, '获取成功');
    }
    catch (error) {
        return handleError(error, '获取失败，请稍后重试', ERROR_CODES.DATA);
    }
}
exports.getPet = getPet;
// =====================================================================
// Handlers 聚合
// =====================================================================
exports.handlers = {
    createPet,
    updatePet,
    deletePet,
    getPet,
    getPetList,
    getPetDetail,
};
// =====================================================================
// Main 入口
// =====================================================================
async function main(event, context) {
    const { action } = event;
    if (!action || !exports.handlers[action]) {
        throw err('INVALID_PARAMS', '无效的操作类型');
    }
    try {
        const PUBLIC_ACTIONS = ['getPet', 'getPetDetail'];
        const requireLogin = !PUBLIC_ACTIONS.includes(action);
        const auth = await verifyAuth(event, { requireLogin });
        logger.info(action, { openid: auth.openid });
        return await exports.handlers[action](event, context, auth);
    }
    catch (error) {
        logger.error(action, error);
        const code = error.code || ERROR_CODES.BUSINESS;
        return handleError(error, error.message, code);
    }
}
exports.main = main;
// =====================================================================
// Runtime shim（CommonJS 兼容）
// =====================================================================
const _mod = module;
_mod.exports = {
    main,
    createPet,
    updatePet,
    deletePet,
    getPet,
    getPetList,
    getPetDetail,
    convertWeight,
    handlers: exports.handlers,
};
_mod.exports.default = _mod.exports;
exports.default = {
    main,
    createPet,
    updatePet,
    deletePet,
    getPet,
    getPetList,
    getPetDetail,
    convertWeight,
    handlers: exports.handlers,
};
