/**
 * i18n CDN 字典 manifest（auto-generated by scripts/build-i18n.js）
 * @generatedAt 2026-09-14T03:25:29.242Z
 * @version 20260914
 */

export type I18nLocale = 'zh-CN' | 'en-US' | 'ja-JP'

export interface I18nManifest {
  version: string
  generatedAt: string
  locales: I18nLocale[]
  codeCount: number
  bizCount: number
  files: {
    errors: string[]
    biz: string[]
    merged: string[]
    all: string[]
  }
}

export const I18N_MANIFEST: I18nManifest

/**
 * 小程序端加载入口（示例）
 *   import { fetchI18nDictionary } from '@/utils/i18n-cdn'
 *   const dict = await fetchI18nDictionary('en-US')
 */
export declare function fetchI18nDictionary(locale: I18nLocale): Promise<Record<string, string>>
