/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
"use strict";
// cloudfunctions/common/cloudbase.ts - 腾讯云开发Node.js SDK初始化配置
// Sprint 35: 迁移到 TypeScript
Object.defineProperty(exports, "__esModule", { value: true });
exports.initializeApiKey = exports.initializeAppSecret = exports.getCloudbase = void 0;
// 引入腾讯云开发Node.js SDK（使用 require 避免引入未提供类型声明的包）
const nodeSdk = require('@cloudbase/node-sdk');
const { initialize, CloudBase } = nodeSdk;
const logger_1 = require("./logger");
const _logger = (0, logger_1.createLogger)('cloudbase');
// 配置1: 使用AppID+Secret初始化方式（推荐用于云函数环境）
const CLOUDBASE_SECRET = process.env.CLOUDBASE_SECRET;
const configAppSecret = {
    appid: process.env.CLOUDBASE_APPID || 'wx481ebe4d7c924f77',
    secret: CLOUDBASE_SECRET,
    env: process.env.CLOUDBASE_ENV || 'cloudbase-d7getcjqy33b13475',
};
// 配置2: 使用API Key初始化方式（适用于需要自定义baseURL的场景）
const configApiKey = {
    baseURL: process.env.CLOUDBASE_BASE_URL || 'https://api.tcloudbasegateway.com/v1/',
    apiKey: process.env.CLOUDBASE_API_KEY,
};
// SDK 实例（懒初始化，避免在测试/CI 环境强制初始化）
let _instance = null;
/**
 * 获取云开发 SDK 实例（懒初始化）
 * 第一次访问时才执行 initialize，CI 环境可以传入 mock 替换
 */
function getCloudbase() {
    if (_instance) {
        return _instance;
    }
    if (process.env.CLOUDBASE_USE_API_KEY === 'true') {
        if (!configApiKey.apiKey) {
            throw new Error('CLOUDBASE_API_KEY 环境变量未配置，无法以 API Key 模式初始化云开发 SDK');
        }
        _instance = new CloudBase(configApiKey);
        if (process.env.NODE_ENV !== 'test') {
            _logger.info('init.apiKey', { mode: 'api_key' });
        }
    }
    else {
        if (!CLOUDBASE_SECRET) {
            throw new Error('CLOUDBASE_SECRET 环境变量未配置，无法初始化云开发 SDK');
        }
        _instance = initialize(configAppSecret);
        if (process.env.NODE_ENV !== 'test') {
            _logger.info('init.appSecret', { mode: 'app_secret' });
        }
    }
    return _instance;
}
exports.getCloudbase = getCloudbase;
/**
 * 显式使用 AppSecret 方式初始化（特殊场景）
 */
function initializeAppSecret() {
    if (!CLOUDBASE_SECRET) {
        throw new Error('CLOUDBASE_SECRET 环境变量未配置，无法初始化云开发 SDK');
    }
    return initialize(configAppSecret);
}
exports.initializeAppSecret = initializeAppSecret;
/**
 * 显式使用 ApiKey 方式初始化（特殊场景）
 */
function initializeApiKey() {
    if (!configApiKey.apiKey) {
        throw new Error('CLOUDBASE_API_KEY 环境变量未配置，无法以 API Key 模式初始化云开发 SDK');
    }
    return new CloudBase(configApiKey);
}
exports.initializeApiKey = initializeApiKey;
// 默认导出（兼容旧 API：require('./common/cloudbase') 返回模块对象）
// 注意：不再在模块顶层调用 getCloudbase()，保持真正的懒初始化
const _mod = module;
_mod.exports.getCloudbase = getCloudbase;
_mod.exports.initializeAppSecret = initializeAppSecret;
_mod.exports.initializeApiKey = initializeApiKey;
exports.default = null; // 懒初始化，使用前请调用 getCloudbase()
