"use strict";
/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WITHDRAWAL_STATUS_LABELS = exports.PAYMENT_STATUS_LABELS = exports.ORDER_STATUS_LABELS = void 0;
exports.ORDER_STATUS_LABELS = {
    pending_payment: '待支付',
    paid: '已支付',
    confirmed: '已确认',
    in_progress: '进行中',
    pending_shipment: '待发货',
    shipped: '已发货',
    completed: '已完成',
    cancelled: '已取消',
    refunded: '已退款',
    deleted: '已删除',
    rejected: '已拒绝',
};
exports.PAYMENT_STATUS_LABELS = {
    unpaid: '未支付',
    paying: '支付中',
    paid: '已支付',
    refunded: '已退款',
    closed: '已关闭',
};
exports.WITHDRAWAL_STATUS_LABELS = {
    pending: '待审核',
    processing: '转账中',
    approved: '待人工转账',
    completed: '已完成',
    rejected: '已拒绝',
};
