/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
/**
 * rate-limit-monitor.ts - 限流监控（TypeScript 源文件 - Sprint 50 新增）
 *
 * 目标：
 *   - 解决 Sprint 17-21 限流系统缺乏可观测性的问题
 *   - 提供 4 类监控指标：
 *     1. 限流命中数（按 type 分组）：{ payment: 12, refund: 5, ... }
 *     2. 限流消费数（按 type 分组）：{ payment: 230, refund: 87, ... }
 *     3. 降级次数（global store 失败 → 内存）：{ total: 3 }
 *     4. 配置来源（db / business_default / fallback）：{ db: 1, business_default: 5, fallback: 0 }
 *   - 提供 webhook 告警接口
 *
 * 用法：
 *   import { recordRateLimitHit, recordRateLimitConsume, getMetrics, getMetricsSnapshot } from './rate-limit-monitor'
 *   import { setAlertWebhook } from './rate-limit-monitor'
 *
 *   // 限流命中时
 *   recordRateLimitHit({ type: 'payment', scope: 'global' })
 *
 *   // 配置告警 webhook
 *   setAlertWebhook(async (event) => {
 *     // 发送钉钉 / 企微 / Slack
 *   })
 *
 *   // 每 60s 拉取一次指标
 *   setInterval(() => {
 *     const m = getMetrics()
 *     console.log(m)
 *   }, 60000)
 *
 * 设计取舍：
 *   - 内存指标 + 周期上报（避免每次请求都远程调用）
 *   - 告警阈值可配置（默认 100 次/分钟触发）
 *   - _resetMetrics() 仅测试用
 *
 * 编译方式：
 *   npx --yes -p typescript@5.4.5 tsc -p tsconfig.common.json
 */

import { err } from './errors'

// ===== 类型定义 =====

export type RateLimitScope = 'global' | 'target'

/** 限流命中事件 */
export interface RateLimitHitEvent {
  type: string
  scope: RateLimitScope
  reason?: string
  timestamp?: number
}

/** 限流消费事件 */
export interface RateLimitConsumeEvent {
  type: string
  scope: RateLimitScope
  allowed: boolean
  timestamp?: number
}

/** 降级事件 */
export interface RateLimitFallbackEvent {
  source: 'global' | 'memory' | 'config_db'
  reason: string
  timestamp?: number
}

/** 配置来源事件 */
export interface RateLimitConfigSourceEvent {
  type: string
  source: 'db' | 'business_default' | 'fallback'
  timestamp?: number
}

/** 告警事件 */
export interface RateLimitAlertEvent {
  level: 'info' | 'warn' | 'critical'
  title: string
  message: string
  metadata: Record<string, unknown>
  timestamp: number
}

/** 告警 webhook 函数 */
export type AlertWebhook = (event: RateLimitAlertEvent) => void | Promise<void>

/** 指标快照 */
export interface RateLimitMetricsSnapshot {
  /** 限流命中数（按 type → scope → count） */
  hits: Record<string, Record<RateLimitScope, number>>
  /** 总命中数 */
  totalHits: number
  /** 限流消费数（按 type → scope → count） */
  consumes: Record<string, Record<RateLimitScope, number>>
  /** 总消费数 */
  totalConsumes: number
  /** 降级次数（按 source） */
  fallbacks: Record<string, number>
  /** 总降级次数 */
  totalFallbacks: number
  /** 配置来源次数（按 type → source → count） */
  configSources: Record<string, Record<string, number>>
  /** 命中率（hits / consumes） */
  hitRate: number
  /** 时间窗口开始 */
  windowStart: number
  /** 时间窗口结束 */
  windowEnd: number
}

// ===== 告警阈值 =====

export const DEFAULT_ALERT_THRESHOLDS = Object.freeze({
  /** 单类型每分钟命中告警阈值 */
  hitsPerMinute: 100,
  /** 降级次数告警阈值 */
  fallbacksPerMinute: 10,
})

// ===== 内存指标存储 =====

interface MetricsStore {
  hits: Map<string, Map<RateLimitScope, number>>
  consumes: Map<string, Map<RateLimitScope, number>>
  fallbacks: Map<string, number>
  configSources: Map<string, Map<string, number>>
  windowStart: number
}

const _store: MetricsStore = {
  hits: new Map(),
  consumes: new Map(),
  fallbacks: new Map(),
  configSources: new Map(),
  windowStart: Date.now(),
}

/** 告警 webhook（可选） */
let _webhook: AlertWebhook | null = null
let _alertThresholds = { ...DEFAULT_ALERT_THRESHOLDS }
const _alertHistory: RateLimitAlertEvent[] = []
const MAX_ALERT_HISTORY = 100

// ===== 告警 webhook =====

/**
 * 设置告警 webhook
 */
export function setAlertWebhook(webhook: AlertWebhook | null): void {
  _webhook = webhook
}

export function getAlertWebhook(): AlertWebhook | null {
  return _webhook
}

/**
 * 设置告警阈值
 */
export function setAlertThresholds(thresholds: Partial<typeof DEFAULT_ALERT_THRESHOLDS>): void {
  _alertThresholds = { ...DEFAULT_ALERT_THRESHOLDS, ...thresholds }
}

export function getAlertThresholds(): typeof DEFAULT_ALERT_THRESHOLDS {
  return { ..._alertThresholds }
}

/**
 * 获取告警历史（最近 N 条）
 */
export function getAlertHistory(): readonly RateLimitAlertEvent[] {
  return _alertHistory.slice()
}

/**
 * 触发告警
 */
async function _triggerAlert(event: RateLimitAlertEvent): Promise<void> {
  _alertHistory.push(event)
  if (_alertHistory.length > MAX_ALERT_HISTORY) {
    _alertHistory.splice(0, _alertHistory.length - MAX_ALERT_HISTORY)
  }
  if (_webhook) {
    try {
      await _webhook(event)
    } catch (e) {
      // eslint-disable-next-line no-console
      console.warn('[rate-limit-monitor] webhook failed:', e && (e as Error).message)
    }
  }
}

// ===== 内部 helper =====

function _incrementMap<K extends string | symbol | number, V extends number>(
  map: Map<K, Map<RateLimitScope, V>> | Map<K, V>,
  k1: K,
  k2?: string | symbol
): void {
  // 重载 1：嵌套 map（hits / consumes）
  if (k2 !== undefined && map instanceof Map) {
    const first = map as unknown as Map<string, Map<string, number>>
    if (!first.has(k1 as unknown as string)) {
      first.set(k1 as unknown as string, new Map())
    }
    const inner = first.get(k1 as unknown as string)!
    const cur = inner.get(k2 as string) || 0
    inner.set(k2 as string, cur + 1)
  }
}

function _incrementNested(
  parent: Map<string, Map<string, number>>,
  key: string,
  subKey: string
): void {
  if (!parent.has(key)) {parent.set(key, new Map())}
  const inner = parent.get(key)!
  inner.set(subKey, (inner.get(subKey) || 0) + 1)
}

function _incrementFlat(map: Map<string, number>, key: string): void {
  map.set(key, (map.get(key) || 0) + 1)
}

// ===== 公开 API：记录事件 =====

/**
 * 记录限流命中（被拦截）
 */
export function recordRateLimitHit(event: RateLimitHitEvent): void {
  _incrementNested(_store.hits, event.type, event.scope)
  // 检查告警
  const total = _store.hits.get(event.type)?.get(event.scope) || 0
  const windowMs = Date.now() - _store.windowStart
  const minutes = Math.max(0.001, windowMs / 60000)
  if (total > _alertThresholds.hitsPerMinute * minutes) {
    void _triggerAlert({
      level: 'warn',
      title: `限流高频命中：${event.type}/${event.scope}`,
      message: `${event.type} 类型在过去 ${Math.round(minutes * 60)}s 命中 ${total} 次，超过阈值 ${_alertThresholds.hitsPerMinute} 次/分钟`,
      metadata: { type: event.type, scope: event.scope, count: total, reason: event.reason },
      timestamp: Date.now(),
    })
  }
}

/**
 * 记录限流消费（无论允许还是拒绝都记录）
 */
export function recordRateLimitConsume(event: RateLimitConsumeEvent): void {
  const subKey = `${event.scope}:${event.allowed ? 'allowed' : 'rejected'}`
  _incrementNested(_store.consumes, event.type, subKey)
}

/**
 * 记录降级（global store 失败 → 内存）
 */
export function recordRateLimitFallback(event: RateLimitFallbackEvent): void {
  _incrementFlat(_store.fallbacks, event.source)
  const total = _store.fallbacks.get(event.source) || 0
  const windowMs = Date.now() - _store.windowStart
  const minutes = Math.max(0.001, windowMs / 60000)
  if (total > _alertThresholds.fallbacksPerMinute * minutes) {
    void _triggerAlert({
      level: 'critical',
      title: `限流系统降级：${event.source}`,
      message: `${event.source} 降级次数过多：${total} 次/${Math.round(minutes * 60)}s`,
      metadata: { source: event.source, count: total, reason: event.reason },
      timestamp: Date.now(),
    })
  }
}

/**
 * 记录配置来源（用于统计配置覆盖度）
 */
export function recordRateLimitConfigSource(event: RateLimitConfigSourceEvent): void {
  _incrementNested(_store.configSources, event.type, event.source)
}

// ===== 公开 API：查询指标 =====

/**
 * 获取指标快照
 */
export function getMetricsSnapshot(reset = false): RateLimitMetricsSnapshot {
  const now = Date.now()
  let totalHits = 0
  const hits: Record<string, Record<RateLimitScope, number>> = {}
  for (const [type, scopes] of _store.hits.entries()) {
    hits[type] = { global: 0, target: 0 }
    for (const [scope, count] of scopes.entries()) {
      hits[type][scope as RateLimitScope] = count
      totalHits += count
    }
  }
  let totalConsumes = 0
  const consumes: Record<string, Record<RateLimitScope, number>> = {}
  for (const [type, scopes] of _store.consumes.entries()) {
    consumes[type] = { global: 0, target: 0 }
    for (const [scope, count] of scopes.entries()) {
      const [realScope, status] = scope.split(':')
      // 同时累计 allowed + rejected 到对应 scope
      consumes[type][realScope as RateLimitScope] =
        (consumes[type][realScope as RateLimitScope] || 0) + count
      totalConsumes += count
    }
  }
  const fallbacks: Record<string, number> = {}
  let totalFallbacks = 0
  for (const [source, count] of _store.fallbacks.entries()) {
    fallbacks[source] = count
    totalFallbacks += count
  }
  const configSources: Record<string, Record<string, number>> = {}
  for (const [type, sources] of _store.configSources.entries()) {
    configSources[type] = {}
    for (const [source, count] of sources.entries()) {
      configSources[type][source] = count
    }
  }
  const snap: RateLimitMetricsSnapshot = {
    hits,
    totalHits,
    consumes,
    totalConsumes,
    fallbacks,
    totalFallbacks,
    configSources,
    hitRate: totalConsumes > 0 ? totalHits / totalConsumes : 0,
    windowStart: _store.windowStart,
    windowEnd: now,
  }
  if (reset) {
    _resetMetrics()
  }
  return snap
}

/**
 * 获取实时指标（不带 reset）
 */
export function getMetrics(): RateLimitMetricsSnapshot {
  return getMetricsSnapshot(false)
}

/**
 * 重置指标（仅测试用）
 */
export function _resetMetrics(): void {
  _store.hits.clear()
  _store.consumes.clear()
  _store.fallbacks.clear()
  _store.configSources.clear()
  _store.windowStart = Date.now()
  _alertHistory.length = 0
}

// ===== 集成：限流核心调用记录 =====

/**
 * 包装 withRateLimit，自动记录指标
 *
 * 用法（推荐替代直接调用 withRateLimit）：
 *   const result = await withRateLimitMonitored(
 *     { userId, type: 'payment' },
 *     () => doSomething()
 *   )
 */
export async function withRateLimitMonitored<T>(
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  mod: typeof import('./risk-rate-limit'),
  input: { userId: string, type: string, targetId?: string, now?: number },
  fn: () => Promise<T>,
  config?: Parameters<typeof mod.withRateLimit>[2]
): Promise<T> {
  let allowed = true
  let scope: RateLimitScope = 'global'
  try {
    const result: T = await mod.withRateLimit(input, fn, config)
    recordRateLimitConsume({ type: input.type, scope, allowed: true })
    return result
  } catch (e: any) {
    if (e && e.code === 'RATE_LIMITED') {
      allowed = false
      recordRateLimitConsume({ type: input.type, scope, allowed: false })
      recordRateLimitHit({ type: input.type, scope, reason: e.message })
      throw e
    }
    throw e
  }
}

// ===== 默认导出 =====

export default {
  recordRateLimitHit,
  recordRateLimitConsume,
  recordRateLimitFallback,
  recordRateLimitConfigSource,
  getMetrics,
  getMetricsSnapshot,
  _resetMetrics,
  setAlertWebhook,
  getAlertWebhook,
  setAlertThresholds,
  getAlertThresholds,
  getAlertHistory,
  withRateLimitMonitored,
  DEFAULT_ALERT_THRESHOLDS,
}

// 避免 unused 警告
void _incrementMap
void err
