/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
"use strict";
/**
 * adminService/constants.ts - 订单类型常量（TypeScript 源文件 - Sprint 33 迁移）
 *
 * 业务功能：
 *   - 集中维护订单类型枚举（mall / hosting / feeding / tuan / activity）
 *   - 提供类型安全的中文显示名称映射
 *
 * 迁移目标：
 *   - 用 `as const` 派生 OrderTypeKey 类型，无需手写 union
 *   - 强类型化 ORDER_TYPE_NAMES（key 必须来自 ORDER_TYPES）
 *   - 编译产物（constants.js）继续被 index.js / services/* 消费
 *
 * 编译方式：
 *   npx --yes -p typescript@5.4.5 tsc -p tsconfig.adminService.json
 *   （运行时仍消费 .js 编译产物）
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ORDER_TYPE_NAMES = exports.ORDER_TYPES = void 0;
exports.ORDER_TYPES = ['mall', 'hosting', 'feeding', 'tuan', 'activity'];
exports.ORDER_TYPE_NAMES = {
    mall: '商城',
    hosting: '寄养',
    feeding: '上门服务',
    tuan: '团购',
    activity: '活动',
};
// Runtime shim: 兼容原 CommonJS 模式 `module.exports = { ... }`
// (消费方 index.js / services/*.js 使用 `require('./constants').ORDER_TYPES` 等，
//  避免消费方需用 .default 才能取到常量)
const _mod = module;
_mod.exports = { ORDER_TYPES: exports.ORDER_TYPES, ORDER_TYPE_NAMES: exports.ORDER_TYPE_NAMES };
const _exports = _mod.exports;
_exports.default = _exports;
exports.default = { ORDER_TYPES: exports.ORDER_TYPES, ORDER_TYPE_NAMES: exports.ORDER_TYPE_NAMES };
