/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
"use strict";
/**
 * feedingService/index.ts - 喂养服务主入口（TypeScript 源文件 - Sprint 41 迁移）
 *
 * 业务功能：
 *   - 喂养师管理（CRUD + 列表筛选）
 *   - 喂养下单（多宠物 + 上门 + 钥匙 + 熟悉度 + 多次访问）
 *   - 订单管理（我的订单 / 详情 / 状态流转 / 喂养师视角订单）
 *   - 佣金记录（status=completed 触发）
 *
 * 共 12 个 action：
 *   1. getFeederList - 喂养师列表
 *   2. getFeederDetail - 喂养师详情
 *   3. createFeederProfile - 创建喂养师档案
 *   4. updateFeederProfile - 更新喂养师档案
 *   5. createFeedingOrder - 创建喂养订单
 *   6. getFeedingOrders - 我的喂养订单
 *   7. updateFeedingOrderStatus - 更新订单状态
 *   8. getOrderStatus - 获取订单状态
 *   9. getFeederOrders - 喂养师视角订单列表
 *  10. getFeedingOrderDetail - 喂养师视角订单详情
 *  11. handleFeedingOrder - 喂养师接单/完成操作
 *  12. getCurrentFeeder - 获取当前用户喂养师档案
 *
 * 迁移目标：
 *   - 强类型化所有 db 操作、handler 签名、返回结构
 *   - 复用 AuthLike / CloudEvent / CloudContext 公共类型
 *   - 与 adminService / partnerService / userService / activityService / mallService 保持类型一致
 *
 * 编译方式：
 *   npx --yes -p typescript@5.4.5 tsc -p tsconfig.feedingService.json
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.main = exports.handlers = exports.getCurrentFeeder = exports.handleFeedingOrder = exports.getFeedingOrderDetail = exports.getFeederOrders = exports.getOrderStatus = exports.updateFeedingOrderStatus = exports.getFeedingOrders = exports.createFeedingOrder = exports.updateFeederProfile = exports.createFeederProfile = exports.getFeederDetail = exports.getFeederList = void 0;
// =====================================================================
// 内部模块初始化（require CommonJS 模块）
// =====================================================================
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { initCloud, handleSuccess, handleError, generateId, ERROR_CODES, paginate } = require('./common/utils');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createLogger } = require('./common/logger');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { writeOperationLog } = require('./common/operation-log');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { verifyAuth } = require('./common/auth-middleware');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { filterFields, FIELD_WHITELISTS } = require('./common/validator');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { err, toResponse, isBusinessError } = require('./common/errors');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createCommissionRecord: createCommissionRecordShared } = require('../common/commission-utils');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createServiceIncomeRecord } = require('./common/service-income-utils');
const { cloud, db } = initCloud();
const logger = createLogger('feedingService');
const _ = db.command;
// =====================================================================
// 字段投影常量
// =====================================================================
const FEEDER_LIST_FIELDS = {
    _id: true, realName: true, nickname: true, avatarUrl: true, address: true,
    pricePerVisit: true, orderCount: true,
    serviceTags: true, serviceTypes: true, status: true, description: true,
    phone: true, gender: true, createdAt: true, beautyInfo: true,
};
const FEEDING_ORDER_FIELDS = {
    _id: true, orderNo: true, orderType: true, feederId: true, ownerId: true, petIds: true,
    petDetails: true, petServices: true,
    startDate: true, endDate: true, visitTimes: true,
    address: true, notes: true,
    keyMethod: true, visitTime: true, feederGender: true,
    familiarity: true, familiarityText: true, familiarityDates: true,
    multiVisit: true, multiVisitText: true, multiVisitDates: true,
    totalAmount: true, originalAmount: true, couponId: true, couponDiscount: true,
    status: true, paymentStatus: true, createdAt: true, updatedAt: true,
};
// =====================================================================
// 辅助函数：佣金记录（使用共享模块）
// =====================================================================
const createCommissionRecord = createCommissionRecordShared;
// =====================================================================
// 辅助函数：合作伙伴权限校验
// =====================================================================
async function checkPartnerPermission(openid, permission) {
    let admin = null;
    try {
        const adminRes = await db.collection('admins').doc(openid).get();
        admin = adminRes.data || null;
    }
    catch (e) {
        admin = null;
    }
    if (!admin || admin.status !== 'active') {
        throw err('PARTNER_REQUIRED', '无合作伙伴权限');
    }
    const roles = admin.roles || [];
    if (roles.includes('super_admin')) {
        return admin;
    }
    const perms = admin.permissions || [];
    if (!perms.includes(permission)) {
        throw err('PERMISSION_DENIED', `权限不足：需要 ${permission} 权限`);
    }
    return admin;
}
// =====================================================================
// 私有辅助函数：刷新宠物头像
// =====================================================================
async function refreshPetAvatars(orders) {
    const allPetIds = [];
    for (const order of orders) {
        if (order.petIds && order.petIds.length > 0) {
            for (const pid of order.petIds) {
                if (!allPetIds.includes(pid)) {
                    allPetIds.push(pid);
                }
            }
        }
    }
    if (allPetIds.length === 0) {
        return;
    }
    const petMap = {};
    const batchSize = 20;
    for (let i = 0; i < allPetIds.length; i += batchSize) {
        const batch = allPetIds.slice(i, i + batchSize);
        try {
            const res = await db.collection('pets')
                .where({ _id: _.in(batch) })
                .field({ _id: true, avatarUrl: true })
                .get();
            for (const pet of (res.data || [])) {
                petMap[pet._id || ''] = pet.avatarUrl || '';
            }
        }
        catch (e) {
            logger.error('refreshPetAvatars_error', e);
        }
    }
    for (const order of orders) {
        if (!order.petDetails || !Array.isArray(order.petDetails)) {
            continue;
        }
        for (const detail of order.petDetails) {
            const petId = detail.id || detail.petId || detail._id;
            if (petId && petMap[petId] !== undefined) {
                detail.avatarUrl = petMap[petId];
            }
        }
    }
}
// =====================================================================
// 状态提示常量
// =====================================================================
const STATUS_TIPS = {
    pending_payment: { title: '待付款', subtitle: '请尽快完成支付', icon: 'clock' },
    confirmed: { title: '订单已确认', subtitle: '平台已接单，将安排服务人员上门', icon: 'success' },
    in_progress: { title: '服务进行中', subtitle: '服务人员正在为您服务', icon: 'progress' },
    completed: { title: '服务已完成', subtitle: '感谢您的使用', icon: 'completed' },
    cancelled: { title: '订单已取消', subtitle: '', icon: 'cancelled' },
};
// =====================================================================
// Handler 1: getFeederList
// =====================================================================
async function getFeederList(event, _context, _auth) {
    const { page = 1, pageSize = 10, location, serviceType } = event;
    let whereQuery;
    if (serviceType === 'beauty') {
        const beautyCondition = _.or({ serviceTypes: _.in(['beauty']) }, { serviceTags: _.in(['美容造型']) });
        if (location) {
            whereQuery = _.and({ status: 'active', serviceArea: _.in([location]) }, beautyCondition);
        }
        else {
            whereQuery = _.and({ status: 'active' }, beautyCondition);
        }
    }
    else {
        whereQuery = { status: 'active' };
        if (location) {
            whereQuery.serviceArea = _.in([location]);
        }
        if (serviceType) {
            whereQuery.serviceTypes = _.in([serviceType]);
        }
    }
    const countResult = await db.collection('feeders').where(whereQuery).count();
    const offset = (page - 1) * pageSize;
    const dataResult = await db.collection('feeders')
        .where(whereQuery)
        .field(FEEDER_LIST_FIELDS)
        .orderBy('rating', 'desc')
        .skip(offset)
        .limit(pageSize)
        .get();
    const result = {
        list: (dataResult.data || []),
        total: countResult.total,
        page,
        pageSize,
        totalPages: Math.ceil(countResult.total / pageSize),
        hasNext: page * pageSize < countResult.total,
    };
    return handleSuccess(result, '获取成功');
}
exports.getFeederList = getFeederList;
// =====================================================================
// Handler 2: getFeederDetail
// =====================================================================
async function getFeederDetail(event, _context, _auth) {
    const { feederId } = event;
    if (!feederId) {
        throw err('INVALID_PARAMS', '缺少喂养师ID');
    }
    try {
        const res = await db.collection('feeders').doc(feederId).get();
        return handleSuccess(res.data, '获取成功');
    }
    catch (error) {
        return handleError(error, '喂养师不存在', ERROR_CODES.NOT_FOUND);
    }
}
exports.getFeederDetail = getFeederDetail;
// =====================================================================
// Handler 3: createFeederProfile
// =====================================================================
async function createFeederProfile(event, _context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { name, avatarUrl, phone, description, serviceArea, pricePerVisit, certifications } = event;
    if (!name) {
        throw err('INVALID_PARAMS', '缺少喂养师名称');
    }
    if (phone && !/^1[3-9]\d{9}$/.test(phone)) {
        throw err('INVALID_PARAMS', '手机号格式不正确');
    }
    const feeder = {
        name,
        avatarUrl: avatarUrl || '',
        phone: phone || '',
        description: description || '',
        serviceArea: serviceArea || [],
        pricePerVisit: Number(pricePerVisit) || 0,
        certifications: certifications || [],
        rating: 0,
        orderCount: 0,
        status: 'pending_review',
        createdBy: openid,
        createdAt: db.serverDate(),
        updatedAt: db.serverDate(),
    };
    feeder._id = generateId('feeder', openid);
    const res = await db.collection('feeders').add({ data: feeder });
    return handleSuccess({ id: res._id }, '创建成功');
}
exports.createFeederProfile = createFeederProfile;
// =====================================================================
// Handler 4: updateFeederProfile
// =====================================================================
async function updateFeederProfile(event, _context, auth) {
    const { feederId } = event;
    const { openid } = auth;
    if (!feederId) {
        throw err('INVALID_PARAMS', '缺少喂养师ID');
    }
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const updateData = {
        updatedAt: db.serverDate(),
        ...filterFields(FIELD_WHITELISTS.feeder, event),
    };
    const existRes = await db.collection('feeders').doc(feederId).get();
    const existData = existRes.data;
    if (existData && existData.createdBy !== openid) {
        try {
            await checkPartnerPermission(openid, 'feeding');
        }
        catch (e) {
            throw err('PERMISSION_DENIED', '无权修改此喂养师档案');
        }
    }
    await db.collection('feeders').doc(feederId).update({ data: updateData });
    return handleSuccess(null, '更新成功');
}
exports.updateFeederProfile = updateFeederProfile;
// =====================================================================
// Handler 5: createFeedingOrder
// =====================================================================
async function createFeedingOrder(event, _context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { feederId, petIds, startDate, endDate, visitTimes, address, notes, keyMethod, visitTime, feederGender, familiarity, familiarityText, familiarityDates, multiVisit, multiVisitText, multiVisitDates, petDetails, petServices, totalAmount, originalAmount, couponId, couponDiscount, orderId, contactPhone, } = event;
    if (!petIds || petIds.length === 0) {
        throw err('INVALID_PARAMS', '请选择宠物');
    }
    if (!contactPhone || !/^1[3-9]\d{9}$/.test(String(contactPhone).trim())) {
        throw err('INVALID_PARAMS', '请填写正确的联系电话');
    }
    // 仅在使用优惠券时，校验优惠后金额下限
    if (couponId && Number(totalAmount) > 0 && Number(totalAmount) < 0.1) {
        throw err('INVALID_PARAMS', '优惠后订单金额必须 ≥ 0.1 元');
    }
    try {
        let feederInfo = {};
        if (feederId) {
            try {
                const feederRes = await db.collection('feeders').doc(feederId).get();
                feederInfo = feederRes.data || {};
            }
            catch (e) {
                feederInfo = {};
            }
        }
        const orderNo = `FD${Date.now()}${Math.random().toString(36).substr(2, 6).toUpperCase()}`;
        const order = {
            orderNo,
            orderType: 'feeding',
            ownerId: openid,
            feederId: feederId || '',
            petIds: petIds || [],
            petDetails: (petDetails || []),
            petServices: petServices || {},
            startDate: startDate || '',
            endDate: endDate || '',
            visitTimes: visitTimes || [],
            address: address || '',
            notes: notes || '',
            keyMethod: keyMethod || '',
            visitTime: visitTime || '',
            feederGender: feederGender || '',
            familiarity: familiarity || '',
            familiarityText: familiarityText || '',
            familiarityDates: familiarityDates || [],
            multiVisit: Number(multiVisit) || 0,
            multiVisitText: multiVisitText || '',
            multiVisitDates: multiVisitDates || [],
            totalAmount: Number(totalAmount) || 0,
            originalAmount: Number(originalAmount) || 0,
            couponId: couponId || '',
            couponDiscount: Number(couponDiscount) || 0,
            contactPhone: String(contactPhone).trim(),
            status: 'pending_payment',
            paymentStatus: 'unpaid',
            createdAt: db.serverDate(),
            updatedAt: db.serverDate(),
        };
        // 允许前端传入自定义 orderId（需符合 fd_ 前缀风格，与 generateId('feeding') 一致），
        // 以便前端 lockCoupon 时使用的 clientOrderId 与最终订单 _id 完全匹配。
        order._id = (typeof orderId === 'string' && /^fd_[a-z0-9_]{4,}$/i.test(orderId))
            ? orderId
            : generateId('feeding', openid);
        const res = await db.collection('feedingOrders').add({ data: order });
        return handleSuccess({ id: res._id, orderNo, totalAmount: order.totalAmount }, '下单成功');
    }
    catch (error) {
        if (error.code) {
            throw error;
        }
        return handleError(error, '下单失败', ERROR_CODES.DATA);
    }
}
exports.createFeedingOrder = createFeedingOrder;
// =====================================================================
// Handler 6: getFeedingOrders
// =====================================================================
async function getFeedingOrders(event, _context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { page = 1, pageSize = 10, status } = event;
    const where = { ownerId: openid };
    if (status) {
        where.status = status;
    }
    const result = await paginate(db, 'feedingOrders', {
        page, pageSize, where, projection: FEEDING_ORDER_FIELDS,
    });
    await refreshPetAvatars(result.list);
    return handleSuccess(result, '获取成功');
}
exports.getFeedingOrders = getFeedingOrders;
// =====================================================================
// Handler 7: updateFeedingOrderStatus
// =====================================================================
async function updateFeedingOrderStatus(event, _context, auth) {
    const { orderId, status } = event;
    const { openid } = auth;
    if (!orderId) {
        throw err('INVALID_PARAMS', '缺少订单ID');
    }
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    if (!status) {
        throw err('INVALID_PARAMS', '缺少状态');
    }
    const VALID_STATUSES = ['confirmed', 'in_progress', 'completed', 'cancelled'];
    if (!VALID_STATUSES.includes(status)) {
        throw err('INVALID_PARAMS', '无效的状态值');
    }
    try {
        const orderRes = await db.collection('feedingOrders').doc(orderId).get();
        if (!orderRes.data) {
            throw err('NOT_FOUND', '订单不存在');
        }
        const order = orderRes.data;
        if (order.ownerId !== openid) {
            throw err('PERMISSION_DENIED', '无权操作该订单');
        }
        const allowedTransitions = {
            pending_payment: ['cancelled'],
            confirmed: ['in_progress', 'cancelled'],
            in_progress: ['completed', 'cancelled'],
            completed: [],
            cancelled: [],
        };
        const allowedNext = allowedTransitions[order.status || ''] || [];
        if (!allowedNext.includes(status)) {
            throw err('BUSINESS_ERROR', '状态变更无效');
        }
        await db.collection('feedingOrders').doc(orderId).update({
            data: { status, updatedAt: db.serverDate() },
        });
        if (status === 'cancelled') {
            // 1. 退回优惠券
            await refundCouponForOrder(orderId, openid).catch((e) => {
                logger.error('refundCouponForOrder failed', { error: e.message || String(e) });
            });

            // 2. 取消收入记录
            try {
                const { cancelServiceIncomeRecord } = require('./common/service-income-utils');
                await cancelServiceIncomeRecord(orderId, 'feeding');
            } catch (incomeErr) {
                logger.warn('cancelServiceIncomeRecord failed', { error: incomeErr?.message });
            }

            // 3. 取消佣金记录
            try {
                const { cancelCommissionRecord } = require('../common/commission-utils');
                await cancelCommissionRecord(orderId);
            } catch (commissionErr) {
                logger.warn('cancelCommissionRecord failed', { error: commissionErr?.message });
            }

            // 4. 调用微信支付退款
            try {
                const totalAmount = Math.round((Number(order.totalAmount) || Number(order.totalPrice) || 0) * 100);
                const finalAmount = Math.round((Number(order.finalAmount) || Number(order.totalAmount) || Number(order.totalPrice) || 0) * 100);
                if (totalAmount > 0 && finalAmount > 0) {
                    await cloud.callFunction({
                        name: 'paymentService',
                        data: {
                            action: 'createRefund',
                            outTradeNo: order.outTradeNo || orderId,
                            refundAmount: finalAmount,
                            totalAmount: totalAmount,
                        },
                    });
                    logger.info('updateFeedingOrderStatus.refundCreated', { orderId, outTradeNo: order.outTradeNo });
                }
            } catch (refundErr) {
                logger.warn('updateFeedingOrderStatus.refundFailed', { error: refundErr?.message || String(refundErr) });
            }
        }
        return handleSuccess(null, '状态更新成功');
    }
    catch (error) {
        if (error.code) {
            throw error;
        }
        return handleError(error, '更新状态失败', ERROR_CODES.DATA);
    }
}
exports.updateFeedingOrderStatus = updateFeedingOrderStatus;
/**
 * 取消订单时退回优惠券
 *
 * 覆盖两种场景：
 *   1) 券已使用（coupon_usage 有记录、status='used'）→ 标记为 refunded
 *   2) 券仅被锁定（coupon_usage 无记录、status='locked'）→ 直接解锁
 *
 * 释放后根据 endTime 决定新状态：过期 → expired，未过期 → unused
 */
async function refundCouponForOrder(orderId, openid) {
    const now = Date.now();

    // 1) 先处理已使用的券（coupon_usage 里有记录）
    const usageRes = await db.collection('coupon_usage').where({ orderId }).limit(10).get();
    if (usageRes.data && usageRes.data.length > 0) {
        for (const usage of usageRes.data) {
            if (usage.status === 'refunded') {continue;}
            const couponId = usage.userCouponId;
            if (!couponId) {continue;}
            const cRes = await db.collection('user_coupons').doc(couponId).get();
            if (!cRes.data) {continue;}
            const c = cRes.data;
            if (c.ownerId !== openid) {continue;}
            if (c.status !== 'used') {continue;}
            const isExpired = c.endTime ? new Date(c.endTime).getTime() < now : false;
            const newStatus = isExpired ? 'expired' : 'unused';
            await db.collection('user_coupons').doc(couponId).update({
                data: { status: newStatus, updatedAt: db.serverDate() },
            });
            await db.collection('coupon_usage').doc(usage._id).update({
                data: { status: 'refunded', refundedAt: db.serverDate(), updatedAt: db.serverDate() },
            });
            await writeOperationLog({
                module: 'user_coupon',
                action: 'refund_on_cancel',
                targetId: couponId,
                targetName: c.templateName || '',
                operatorId: openid,
                operatorName: openid,
                beforeData: { status: 'used', orderId },
                afterData: { status: newStatus, orderId },
            });
        }
    }

    // 2) 再处理仅被锁定的券（用户取消时还未支付成功）
    //    关键修复：旧版只查 coupon_usage，导致 locked 状态的券被遗弃为"死锁"
    const lockedRes = await db.collection('user_coupons')
        .where({ lockedOrderId: orderId, status: 'locked' })
        .limit(10)
        .get();
    if (lockedRes.data && lockedRes.data.length > 0) {
        for (const c of lockedRes.data) {
            if (c.ownerId !== openid) {continue;}
            const isExpired = c.endTime ? new Date(c.endTime).getTime() < now : false;
            const newStatus = isExpired ? 'expired' : 'unused';
            await db.collection('user_coupons').doc(c._id).update({
                data: {
                    status: newStatus,
                    lockedOrderId: '',
                    updatedAt: db.serverDate(),
                },
            });
            await writeOperationLog({
                module: 'user_coupon',
                action: 'unlock_on_cancel',
                targetId: c._id,
                targetName: c.templateName || '',
                operatorId: openid,
                operatorName: openid,
                beforeData: { status: 'locked', orderId },
                afterData: { status: newStatus, orderId },
            });
        }
    }
}
// =====================================================================
// Handler 8: getOrderStatus
// =====================================================================
async function getOrderStatus(event, _context, auth) {
    const { orderId } = event;
    const { openid } = auth;
    if (!orderId) {
        throw err('INVALID_PARAMS', '缺少订单ID');
    }
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    try {
        const orderRes = await db.collection('feedingOrders').doc(orderId).get();
        if (!orderRes.data) {
            throw err('NOT_FOUND', '订单不存在');
        }
        const order = orderRes.data;
        if (order.ownerId !== openid) {
            throw err('PERMISSION_DENIED', '无权查看该订单');
        }
        let feederInfo = { feederName: '', feederPhone: '', feederAvatar: '' };
        if (order.feederId) {
            try {
                const feederRes = await db.collection('feeders').doc(order.feederId).get();
                const feederData = feederRes.data;
                feederInfo = {
                    feederName: feederData?.name || feederData?.realName || '',
                    feederPhone: feederData?.phone || '',
                    feederAvatar: feederData?.avatarUrl || '',
                };
            }
            catch (e) {
                feederInfo = { feederName: '', feederPhone: '', feederAvatar: '' };
            }
        }
        await refreshPetAvatars([order]);
        return handleSuccess({
            ...order,
            status: order.status,
            paymentStatus: order.paymentStatus || '',
            totalPrice: order.totalAmount || order.totalPrice || 0,
            feederName: feederInfo.feederName,
            feederPhone: feederInfo.feederPhone,
            feederAvatar: feederInfo.feederAvatar,
            tip: STATUS_TIPS[order.status || ''] || { title: '未知状态', subtitle: '', icon: '' },
        }, '获取成功');
    }
    catch (error) {
        if (error.code) {
            throw error;
        }
        return handleError(error, '获取订单状态失败', ERROR_CODES.DATA);
    }
}
exports.getOrderStatus = getOrderStatus;
// =====================================================================
// Handler 9: getFeederOrders
// =====================================================================
async function getFeederOrders(event, _context, auth) {
    const { openid } = auth;
    const { status, page = 1, pageSize = 10 } = event;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    await checkPartnerPermission(openid, 'feeding');
    const feederRes = await db.collection('feeders')
        .where({ createdBy: openid })
        .field({ _id: true })
        .limit(100)
        .get();
    const feederIds = (feederRes.data || []).map((f) => f._id || '').filter(Boolean);
    if (feederIds.length === 0) {
        return handleSuccess({ list: [], total: 0, page, pageSize, totalPages: 0, hasNext: false }, '获取成功');
    }
    const where = { feederId: _.in(feederIds) };
    if (status) {
        where.status = status;
    }
    const result = await paginate(db, 'feedingOrders', {
        page, pageSize, where, projection: FEEDING_ORDER_FIELDS,
    });
    await refreshPetAvatars(result.list);
    return handleSuccess(result, '获取成功');
}
exports.getFeederOrders = getFeederOrders;
// =====================================================================
// Handler 10: getFeedingOrderDetail
// =====================================================================
async function getFeedingOrderDetail(event, _context, auth) {
    const { openid } = auth;
    const { orderId } = event;
    if (!orderId) {
        throw err('INVALID_PARAMS', '缺少订单ID');
    }
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    await checkPartnerPermission(openid, 'feeding');
    const orderRes = await db.collection('feedingOrders').doc(orderId).get();
    if (!orderRes.data) {
        throw err('ORDER_NOT_FOUND', '订单不存在', { orderId });
    }
    const order = orderRes.data;
    await refreshPetAvatars([order]);
    return handleSuccess({ ...order }, '获取成功');
}
exports.getFeedingOrderDetail = getFeedingOrderDetail;
// =====================================================================
// Handler 11: handleFeedingOrder
// =====================================================================
async function handleFeedingOrder(event, _context, auth) {
    const { openid } = auth;
    const { orderId, operation } = event;
    if (!orderId) {
        throw err('INVALID_PARAMS', '缺少订单ID');
    }
    if (!operation) {
        throw err('INVALID_PARAMS', '缺少操作类型');
    }
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    await checkPartnerPermission(openid, 'feeding');
    const OPERATION_MAP = { confirm: 'confirmed', complete: 'completed' };
    const targetStatus = OPERATION_MAP[operation];
    if (!targetStatus) {
        throw err('INVALID_PARAMS', '无效的操作类型');
    }
    const orderRes = await db.collection('feedingOrders').doc(orderId).get();
    if (!orderRes.data) {
        throw err('ORDER_NOT_FOUND', '订单不存在', { orderId });
    }
    const order = orderRes.data;
    const TRANSITIONS = {
        pending_payment: ['confirmed'],
        confirmed: ['completed'],
        in_progress: ['completed'],
    };
    const allowed = TRANSITIONS[order.status || ''] || [];
    if (!allowed.includes(targetStatus)) {
        throw err('ORDER_STATUS_INVALID', `无法从 ${order.status} 变更为 ${targetStatus}`, { from: order.status, to: targetStatus });
    }
    await db.collection('feedingOrders').doc(orderId).update({
        data: { status: targetStatus, updatedAt: db.serverDate() },
    });
    if (targetStatus === 'completed') {
        await createCommissionRecord('feeding', { ...order, totalAmount: order.totalPrice }, {
            configCollection: 'system_config',
            customLogger: logger,
        });
        
        // Create feeding income record for feeder creator
        if (order.feederId) {
            try {
                const feederRes = await db.collection('feeders').doc(order.feederId).get();
                const feeder = feederRes.data;
                if (feeder && feeder.createdBy) {
                    const amount = Number(order.totalAmount) || 0;
                    if (amount > 0) {
                        await createServiceIncomeRecord(
                            feeder.createdBy,
                            'feeding',
                            order._id,
                            amount,
                            order.orderNo || '',
                            '上门服务收入'
                        );
                    }
                }
            } catch (e) {
                logger.warn('handleFeedingOrder.createServiceIncomeRecord', {
                    orderId,
                    feederId: order.feederId,
                    msg: e.message
                });
            }
        }
    }
    return handleSuccess(null, '操作成功');
}
exports.handleFeedingOrder = handleFeedingOrder;
// =====================================================================
// Handler 12: getCurrentFeeder
// =====================================================================
async function getCurrentFeeder(event, _context, auth) {
    const { openid } = auth;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const { serviceType } = event;
    const where = { createdBy: openid };
    if (serviceType) {
        where.serviceTypes = _.in([serviceType]);
    }
    const feederRes = await db.collection('feeders')
        .where(where)
        .limit(1)
        .get();
    if (!feederRes.data || feederRes.data.length === 0) {
        return handleSuccess(null, '未找到喂养师档案');
    }
    return handleSuccess(feederRes.data[0], '获取成功');
}
exports.getCurrentFeeder = getCurrentFeeder;
// =====================================================================
// Handlers 聚合
// =====================================================================
exports.handlers = {
    getFeederList,
    getFeederDetail,
    createFeederProfile,
    updateFeederProfile,
    createFeedingOrder,
    getFeedingOrders,
    getOrderStatus,
    updateFeedingOrderStatus,
    getFeederOrders,
    getFeedingOrderDetail,
    handleFeedingOrder,
    getCurrentFeeder,
};
// =====================================================================
// Main 入口
// =====================================================================
async function main(event, context) {
    const { action } = event;
    if (!action || !exports.handlers[action]) {
        throw err('INVALID_PARAMS', '无效的操作类型');
    }
    const AUTH_REQUIRED_ACTIONS = [
        'createFeederProfile', 'updateFeederProfile', 'createFeedingOrder',
        'updateFeedingOrderStatus', 'getFeedingOrders', 'getOrderStatus',
        'getFeederOrders', 'getFeedingOrderDetail', 'handleFeedingOrder', 'getCurrentFeeder',
    ];
    const requireLogin = AUTH_REQUIRED_ACTIONS.includes(action);
    try {
        const auth = await verifyAuth(event, { requireLogin });
        logger.info(action, { openid: auth.openid });
        return await exports.handlers[action](event, context, auth);
    }
    catch (error) {
        logger.error(action, error);
        if (isBusinessError(error)) {
            return toResponse(error);
        }
        const code = error.code || ERROR_CODES.BUSINESS;
        return handleError(error, error.message, code);
    }
}
exports.main = main;
// =====================================================================
// Runtime shim（CommonJS 兼容）
// =====================================================================
const _mod = module;
_mod.exports = {
    main,
    getFeederList,
    getFeederDetail,
    createFeederProfile,
    updateFeederProfile,
    createFeedingOrder,
    getFeedingOrders,
    getOrderStatus,
    updateFeedingOrderStatus,
    getFeederOrders,
    getFeedingOrderDetail,
    handleFeedingOrder,
    getCurrentFeeder,
    handlers: exports.handlers,
};
_mod.exports.default = _mod.exports;
exports.default = {
    main,
    getFeederList,
    getFeederDetail,
    createFeederProfile,
    updateFeederProfile,
    createFeedingOrder,
    getFeedingOrders,
    getOrderStatus,
    updateFeedingOrderStatus,
    getFeederOrders,
    getFeedingOrderDetail,
    handleFeedingOrder,
    getCurrentFeeder,
    handlers: exports.handlers,
};
