/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
"use strict";
/**
 * application.ts - 合作伙伴申请服务（TypeScript 源文件 - Sprint 36 迁移）
 *
 * 业务功能：
 *   - 提交合作伙伴申请（submitApplication）
 *   - 查询申请状态（getApplicationStatus）
 *   - 查询合作伙伴权限（getMyPermissions）
 *
 * 迁移目标：
 *   - 修复原 application.js line 1 的路径错误（./common/errors → ../common/errors）
 *   - 强类型化所有 db 操作、handler 签名、返回结构
 *
 * 编译方式：
 *   npx --yes -p typescript@5.4.5 tsc -p tsconfig.partnerService.json
 *
 * 数据库索引建议（运维需在对应集合上创建）：
 *   admin_applications: { openid: 1, status: 1, createdAt: -1 } - 覆盖 pending 申请查询
 *   admins: { _id: 1, status: 1 }                                - 覆盖合作伙伴权限查询
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.getMyCommissionRates = exports.getMyPermissions = exports.getApplicationStatus = exports.submitApplication = void 0;
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { err } = require('../common/errors');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { initCloud, handleSuccess, handleError, generateId, ERROR_CODES } = require('../common/utils');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createLogger } = require('../common/logger');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { db } = initCloud();
const logger = createLogger('partnerService:application');
// =====================================================================
// 校验常量
// =====================================================================
// 大陆手机号格式（11 位，1 开头，第二位 3-9）
const PHONE_REGEX = /^1[3-9]\d{9}$/;
const MAX_REALNAME_LEN = 30;
const MAX_REASON_LEN = 500;
const MAX_PERMISSIONS_COUNT = 20;
// H2: 敏感权限禁用清单——合作伙伴申请不得包含平台级管理权限
//   防止用户申请 super_admin/admin/operator 等敏感角色权限，审批人疏忽批准导致权限越权
//   业务级合作伙伴权限（如 'partner'、'order:list' 等）由 adminService 审批时分配
const FORBIDDEN_PERMISSIONS = Object.freeze([
    'super_admin',
    'admin',
    'operator',
    'viewer',
    'all', // 通配权限，仅 super_admin 隐含
    'finance',
    'finance_admin',
]);
// =====================================================================
// Handler 实现
// =====================================================================
async function submitApplication(event, context, auth) {
    const { openid } = auth;
    const { realName, phone, reason, permissions } = event;
    // M9: 参数校验——非空 + 长度 + 格式 + 类型
    if (!realName || typeof realName !== 'string' || !realName.trim()) {
        throw err('INVALID_PARAMS', '请填写真实姓名');
    }
    if (realName.length > MAX_REALNAME_LEN) {
        throw err('INVALID_PARAMS', `姓名长度不能超过 ${MAX_REALNAME_LEN} 字`);
    }
    if (!phone || typeof phone !== 'string' || !PHONE_REGEX.test(phone)) {
        throw err('INVALID_PARAMS', '请填写有效的手机号');
    }
    if (!reason || typeof reason !== 'string' || !reason.trim()) {
        throw err('INVALID_PARAMS', '请填写申请理由');
    }
    if (reason.length > MAX_REASON_LEN) {
        throw err('INVALID_PARAMS', `申请理由长度不能超过 ${MAX_REASON_LEN} 字`);
    }
    // permissions 数组元素必须为非空字符串，且数量受限
    let safePermissions = [];
    if (permissions !== undefined) {
        if (!Array.isArray(permissions)) {
            throw err('INVALID_PARAMS', 'permissions 必须为数组');
        }
        if (permissions.length > MAX_PERMISSIONS_COUNT) {
            throw err('INVALID_PARAMS', `权限项不能超过 ${MAX_PERMISSIONS_COUNT} 个`);
        }
        safePermissions = permissions.filter((p) => typeof p === 'string' && p.trim().length > 0);
        // H2: 拦截敏感权限申请——防止用户申请 super_admin/admin 等平台级管理权限
        //   审批人若疏忽批准即授予高危权限，故在申请阶段直接拒绝
        const forbidden = safePermissions.filter(p => FORBIDDEN_PERMISSIONS.includes(p.trim()));
        if (forbidden.length > 0) {
            throw err('INVALID_PARAMS', `不允许申请以下权限：${forbidden.join(', ')}`);
        }
    }
    try {
        const existingRes = await db.collection('admin_applications')
            .where({ openid, status: 'pending' }).limit(1).get();
        if (existingRes.data && existingRes.data.length > 0) {
            throw err('BUSINESS_ERROR', '您已有待审核申请');
        }
        let admin = {};
        try {
            const adminRes = await db.collection('admins').doc(openid).get();
            admin = adminRes.data || {};
        }
        catch (e) {
            // L4: admins 集合未初始化或查询异常时降级为空对象（首次申请场景）
            logger.warn('submitApplication.admins.fetch', {
                openid, msg: e.message,
            });
            admin = {};
        }
        // M3: 拦截已是 active 合作伙伴的用户重复提交申请
        //   原：仅检查 pending 申请，未检查已是 active 合作伙伴，可重复提交无效申请
        if (admin && admin.status === 'active' && admin.isPartner) {
            throw err('BUSINESS_ERROR', '您已是合作伙伴，无需重复申请');
        }
        const application = {
            _id: generateId('application', openid),
            openid: openid || '',
            nickName: admin.nickName || '',
            avatarUrl: admin.avatarUrl || '',
            realName: realName.trim(),
            phone,
            role: 'partner',
            permissions: safePermissions,
            reason: reason.trim(),
            status: 'pending',
            createdAt: db.serverDate(),
            updatedAt: db.serverDate(),
        };
        const res = await db.collection('admin_applications').add({ data: application });
        return handleSuccess({ id: res._id }, '提交成功');
    }
    catch (error) {
        logger.error('submitApplication', error);
        return handleError(error, '提交申请失败', ERROR_CODES.DATA);
    }
}
exports.submitApplication = submitApplication;
async function getApplicationStatus(event, context, auth) {
    const { openid } = auth;
    try {
        // H3: 字段投影——仅返回前端展示所需字段，避免 PII 泄露
        //   原：直接返回 res.data[0]，含 phone/realName/permissions 等敏感字段
        //   新：仅返回 _id/status/createdAt/rejectedReason/reason 等展示字段
        const res = await db.collection('admin_applications')
            .where({ openid, status: 'pending' })
            .field({
            _id: true,
            status: true,
            createdAt: true,
            updatedAt: true,
            reason: true,
            rejectedReason: true,
        })
            .limit(1)
            .get();
        const hasPending = res.data && res.data.length > 0;
        return handleSuccess({
            hasPending,
            application: hasPending ? res.data[0] : null,
        });
    }
    catch (error) {
        logger.error('getApplicationStatus', error);
        return handleError(error, '获取申请状态失败', ERROR_CODES.DATA);
    }
}
exports.getApplicationStatus = getApplicationStatus;
async function getMyPermissions(event, context, auth) {
    const { openid } = auth;
    let admin = null;
    try {
        const adminRes = await db.collection('admins').doc(openid).get();
        admin = adminRes.data;
    }
    catch (e) {
        // L4: 静默吞错改为告警，便于排查权限查询异常
        logger.warn('getMyPermissions.admins.fetch', {
            openid, msg: e.message,
        });
        admin = null;
    }
    if (!admin || admin.status !== 'active') {
        return handleSuccess({ isPartner: false });
    }
    return handleSuccess({ isPartner: admin.isPartner || false });
}
exports.getMyPermissions = getMyPermissions;
/**
 * 获取我的佣金比例（迁移自 adminService 旧版：前端收入页展示各板块佣金率）
 * 费率来源：admins.commissionRates（自定义）> system_config.commission_rates（全局）
 */
async function getMyCommissionRates(event, context, auth) {
    const openid = auth.openid;
    if (!openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    try {
        let admin = null;
        try {
            const adminRes = await db.collection('admins').doc(openid).get();
            admin = adminRes.data;
        }
        catch (e) {
            logger.warn('getMyCommissionRates.admins.fetch', { openid, msg: e.message });
        }
        let globalRates = {};
        try {
            const configRes = await db.collection('system_config').doc('commission_rates').get();
            globalRates = (configRes.data || {});
        }
        catch (e) {
            logger.warn('getMyCommissionRates.system_config', { msg: e.message });
        }
        const { pickRate } = require('../common/commission-utils');
        const ORDER_TYPES = ['tuan', 'mall', 'activity', 'feeding', 'boarding'];
        const customRates = (admin && admin.commissionRates) || {};
        const rates = {};
        ORDER_TYPES.forEach((type) => {
            // pickRate 按 RATE_KEY_ALIASES 依次尝试 boarding/hosting/order，取首个非零值；
            // 同时把结果写入 boarding 与 hosting 两个键，兼容前端（用 hosting）与未来（用 boarding）读侧
            const custom = pickRate(customRates, type);
            const global = pickRate(globalRates, type);
            const value = custom > 0 ? custom : (global > 0 ? global : 0);
            rates[type] = value;
            if (type === 'boarding') {
                rates['hosting'] = value;
            }
        });
        return handleSuccess({ rates, hasCustomRates: Boolean(admin && admin.commissionRates) });
    }
    catch (error) {
        logger.error('getMyCommissionRates', error);
        return handleError(error, '获取佣金比例失败', ERROR_CODES.DATA);
    }
}
exports.getMyCommissionRates = getMyCommissionRates;
// =====================================================================
// Runtime shim: CommonJS 兼容
// =====================================================================
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const _mod = module;
_mod.exports = {
    submitApplication,
    getApplicationStatus,
    getMyPermissions,
    getMyCommissionRates,
};
_mod.exports.default = _mod.exports;
exports.default = {
    submitApplication,
    getApplicationStatus,
    getMyPermissions,
    getMyCommissionRates,
};
