#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * TypeScript to JavaScript build helper for common modules
 * - Runs tsc with tsconfig.common.json
 * - Prepends /* eslint-disable *\/ marker to errors.js so the generated
 *   file does not get flagged by project's strict style rules.
 */
const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const TARGETS = [
  path.join(ROOT, 'cloudfunctions', 'common', 'errors.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'errors-i18n.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'logger.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'cache.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'state-machine.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'idempotency.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'date-holidays.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'date-range.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'validator.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'risk-control.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'risk-rate-limit.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'rate-limit-store.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'utils.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'auth-middleware.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'permissions.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'normalize.js'),
  path.join(ROOT, 'cloudfunctions', 'common', 'query-builders.js'),
]
const DISABLE = '/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */'

console.log('[build:common] running tsc ...')
execSync('npx --yes -p typescript@5.4.5 tsc -p tsconfig.common.json', {
  cwd: ROOT,
  stdio: 'inherit',
})

for (const TARGET of TARGETS) {
  if (fs.existsSync(TARGET)) {
    const original = fs.readFileSync(TARGET, 'utf8')
    if (!original.startsWith(DISABLE)) {
      fs.writeFileSync(TARGET, DISABLE + '\n' + original)
      const rel = path.relative(ROOT, TARGET)
      console.log('[build:common] prepended eslint-disable to ' + rel)
    }
  }
}

console.log('[build:common] done.')
