/* eslint-disable -- auto-generated by tsc; style controlled by tsconfig */
"use strict";
/**
 * couponService/index.ts - 优惠券服务主入口（TypeScript 源文件 - Sprint 43 迁移）
 *
 * 业务功能：
 *   - 我的优惠券（按状态查询）
 *   - 可用优惠券（订单计算折扣）
 *   - 可领取模板（领券中心）
 *   - 弹窗优惠券（指定页面）
 *   - 优惠券生命周期：领取 → 锁定（订单）→ 核销（支付完成）/ 解锁（取消）
 *
 * 共 8 个 action：
 *   1. getMyCoupons - 我的优惠券
 *   2. getAvailableCoupons - 可用优惠券
 *   3. getClaimableTemplates - 可领取模板
 *   4. getPopupCoupon - 弹窗优惠券
 *   5. claimCoupon - 领取优惠券
 *   6. lockCoupon - 锁定优惠券（订单创建时）
 *   7. useCoupon - 核销优惠券（订单完成时）
 *   8. unlockCoupon - 解锁优惠券（订单取消时）
 *
 * 优惠券类型：
 *   - fixed_amount / full_reduction：固定金额（rules.reduceAmount）
 *   - discount：折扣率（rules.discountRate，可选 rules.maxReduceAmount 封顶）
 *
 * 状态流转：unused → locked → used
 *         或：unused → locked → expired（解锁时已过期）
 *
 * 迁移目标：
 *   - 强类型化所有 db 操作、handler 签名、返回结构
 *   - 复用 AuthLike / CloudEvent / CloudContext 公共类型
 *   - 优惠券规则 / 状态 / 类型强类型化
 *   - 与 adminService / partnerService / userService / activityService / mallService / feedingService / hostService 保持类型一致
 *
 * 编译方式：
 *   npx --yes -p typescript@5.4.5 tsc -p tsconfig.couponService.json
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.main = exports.handlers = exports.getPopupCoupon = exports.unlockCoupon = exports.useCoupon = exports.lockCoupon = exports.claimCoupon = exports.getClaimableTemplates = exports.getAvailableCoupons = exports.getMyCoupons = exports.calculateCouponDiscount = exports.generateCouponCode = void 0;
// =====================================================================
// 内部模块初始化（require CommonJS 模块）
// =====================================================================
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { initCloud, handleSuccess, handleError, generateId, ERROR_CODES, paginate } = require('./common/utils');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createLogger } = require('./common/logger');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { writeOperationLog } = require('./common/operation-log');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { verifyAuth } = require('./common/auth-middleware');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { err } = require('./common/errors');
const { db } = initCloud();
const logger = createLogger('couponService');
const _ = db.command;
// =====================================================================
// 辅助函数：生成优惠券码
// =====================================================================
function generateCouponCode() {
    const prefix = 'CP';
    const timestamp = Date.now().toString(36).toUpperCase();
    const random = Math.random().toString(36).substr(2, 6).toUpperCase();
    return `${prefix}${timestamp}${random}`;
}
exports.generateCouponCode = generateCouponCode;
// =====================================================================
// 辅助函数：计算优惠券折扣
// =====================================================================
function calculateCouponDiscount(coupon, orderAmount) {
    const { type, rules } = coupon;
    if (!rules) {
        return { eligible: false, message: '优惠券规则缺失' };
    }
    if (rules.threshold && orderAmount < rules.threshold) {
        return { eligible: false, message: `订单金额未达到满${rules.threshold}元使用门槛` };
    }
    let discountAmount = 0;
    switch (type) {
        case 'fixed_amount':
        case 'full_reduction':
            discountAmount = rules.reduceAmount || 0;
            break;
        case 'discount':
            discountAmount = orderAmount * (1 - (rules.discountRate || 1));
            if (rules.maxReduceAmount && rules.maxReduceAmount > 0) {
                discountAmount = Math.min(discountAmount, rules.maxReduceAmount);
            }
            break;
        default:
            return { eligible: false, message: '未知优惠券类型' };
    }
    discountAmount = Math.min(discountAmount, orderAmount);
    discountAmount = Math.round(discountAmount * 100) / 100;
    return { eligible: true, discountAmount };
}
exports.calculateCouponDiscount = calculateCouponDiscount;
// =====================================================================
// Handler 1: getMyCoupons
// =====================================================================
async function getMyCoupons(event, _context, auth) {
    const { status, page = 1, pageSize = 20 } = event;
    if (!auth.openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const where = { ownerId: auth.openid };
    if (status) {
        where.status = status;
    }
    const result = await paginate(db, 'user_coupons', {
        page, pageSize, where,
        orderBy: { field: 'createdAt', direction: 'desc' },
    });
    return handleSuccess(result);
}
exports.getMyCoupons = getMyCoupons;
// =====================================================================
// Handler 2: getAvailableCoupons
// =====================================================================
async function getAvailableCoupons(event, _context, auth) {
    const { business, items, amount } = event;
    if (!auth.openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    if (!business) {
        throw err('INVALID_PARAMS', '缺少业务类型');
    }
    const now = new Date();
    const couponWhere = {
        ownerId: auth.openid,
        status: 'unused',
        startTime: _.lte(now),
        endTime: _.gte(now),
        applicableScopes: _.or([
            _.eq([]),
            _.size(0),
            _.in([business]),
        ]),
    };
    const coupons = await db.collection('user_coupons').where(couponWhere).get();
    const available = [];
    for (const coupon of (coupons.data || [])) {
        if (items && items.length > 0 && coupon.applicableItemIds && coupon.applicableItemIds.length > 0) {
            const hasMatch = items.some((item) => coupon.applicableItemIds?.includes(item));
            if (!hasMatch) {
                continue;
            }
        }
        const result = calculateCouponDiscount(coupon, amount || 0);
        if (result.eligible && result.discountAmount !== undefined) {
            available.push({
                _id: coupon._id,
                templateId: coupon.templateId,
                templateName: coupon.templateName,
                couponCode: coupon.couponCode,
                type: coupon.type,
                rules: coupon.rules,
                discountAmount: result.discountAmount,
                endTime: coupon.endTime,
            });
        }
    }
    available.sort((a, b) => b.discountAmount - a.discountAmount);
    return handleSuccess(available);
}
exports.getAvailableCoupons = getAvailableCoupons;
// =====================================================================
// Handler 3: getClaimableTemplates
// =====================================================================
async function getClaimableTemplates(event, _context, auth) {
    const { business, page = 1, pageSize = 20 } = event;
    if (!auth.openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    const where = {
        status: 'active',
        claimable: true,
        remaining: _.gt(0),
    };
    if (business) {
        where.applicableScopes = _.in([business]);
    }
    const result = await paginate(db, 'coupon_templates', {
        page, pageSize, where,
        orderBy: { field: 'createdAt', direction: 'desc' },
    });
    // 补充每个模板当前用户已领取数量
    if (result.list && result.list.length > 0) {
        const templateIds = result.list.map((t) => t._id || '').filter(Boolean);
        const claimedRes = await db.collection('user_coupons')
            .where({ templateId: _.in(templateIds), ownerId: auth.openid, status: _.in(['unused', 'locked']) })
            .get();
        const claimedMap = {};
        for (const c of (claimedRes.data || [])) {
            if (c.templateId) {
                claimedMap[c.templateId] = (claimedMap[c.templateId] || 0) + 1;
            }
        }
        for (const t of result.list) {
            const id = t._id || '';
            t.claimedCount = claimedMap[id] || 0;
            t.canClaim = (t.claimedCount || 0) < (t.perUserLimit || 1);
        }
    }
    return handleSuccess(result);
}
exports.getClaimableTemplates = getClaimableTemplates;
// =====================================================================
// Handler 4: claimCoupon
// =====================================================================
async function claimCoupon(event, _context, auth) {
    const { templateId } = event;
    if (!auth.openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    if (!templateId) {
        throw err('INVALID_PARAMS', '缺少模板ID');
    }
    const templateRes = await db.collection('coupon_templates').where({ _id: templateId }).limit(1).get();
    if (templateRes.data.length === 0) {
        throw err('NOT_FOUND', '模板不存在');
    }
    const template = templateRes.data[0];
    if (template.status !== 'active') {
        throw err('BUSINESS_ERROR', '模板未启用');
    }
    if ((template.remaining || 0) <= 0) {
        throw err('BUSINESS_ERROR', '优惠券已领完');
    }
    // claimable 仅限制领券中心主动领取，弹窗/手动发放不受此限制
    const source = event.source || 'claim';
    if (source === 'claim' && !template.claimable) {
        throw err('BUSINESS_ERROR', '该优惠券不支持领取');
    }
    const existingCount = await db.collection('user_coupons')
        .where({ templateId, ownerId: auth.openid, status: _.in(['unused', 'locked']) })
        .count();
    if (existingCount.total >= (template.perUserLimit || 1)) {
        throw err('COUPON_LIMIT_REACHED', `每人限领${template.perUserLimit || 1}张`);
    }
    const now = new Date();
    const startTime = template.validFrom ? new Date(template.validFrom) : now;
    let endTime;
    if (template.validDays) {
        endTime = new Date(now.getTime() + template.validDays * 24 * 60 * 60 * 1000);
    }
    else if (template.validTo) {
        endTime = new Date(template.validTo);
    }
    else {
        endTime = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
    }
    if (endTime <= now) {
        throw err('BUSINESS_ERROR', '该优惠券已过期');
    }
    const coupon = {
        templateId,
        templateName: template.name,
        ownerId: auth.openid,
        couponCode: generateCouponCode(),
        type: template.type,
        rules: template.rules,
        applicableScopes: template.applicableScopes,
        applicableItemIds: template.applicableItemIds,
        status: 'unused',
        source,
        receivedAt: db.serverDate(),
        startTime,
        endTime,
        createdAt: db.serverDate(),
        updatedAt: db.serverDate(),
    };
    coupon._id = generateId('coupon', auth.openid);
    await db.collection('user_coupons').add({ data: coupon });
    await db.collection('coupon_templates').doc(templateId).update({
        data: { remaining: _.inc(-1), updatedAt: db.serverDate() },
    });
    await writeOperationLog({
        module: 'user_coupon',
        action: 'claim',
        targetId: coupon._id,
        targetName: template.name,
        operatorId: auth.openid,
        operatorName: auth.nickName || auth.openid,
        afterData: coupon,
    });
    return handleSuccess(coupon, '领取成功');
}
exports.claimCoupon = claimCoupon;
// =====================================================================
// Handler 5: lockCoupon
// =====================================================================
async function lockCoupon(event, _context, auth) {
    const { couponId, orderId, orderType, business } = event;
    if (!auth.openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    if (!couponId) {
        throw err('INVALID_PARAMS', '缺少优惠券ID');
    }
    if (!orderId) {
        throw err('INVALID_PARAMS', '缺少订单ID');
    }
    const couponRes = await db.collection('user_coupons').where({ _id: couponId }).limit(1).get();
    if (couponRes.data.length === 0) {
        throw err('NOT_FOUND', '优惠券不存在');
    }
    const coupon = couponRes.data[0];
    if (coupon.ownerId !== auth.openid) {
        throw err('PERMISSION_DENIED', '无权操作此优惠券');
    }
    if (coupon.status !== 'unused') {
        throw err('COUPON_STATUS_INVALID', `当前状态: ${coupon.status}`);
    }
    const now = new Date();
    if (coupon.startTime && now < new Date(coupon.startTime)) {
        throw err('BUSINESS_ERROR', '优惠券尚未生效');
    }
    if (coupon.endTime && now > new Date(coupon.endTime)) {
        throw err('BUSINESS_ERROR', '优惠券已过期');
    }
    await db.collection('user_coupons').doc(couponId).update({
        data: {
            status: 'locked',
            lockedOrderId: orderId,
            updatedAt: db.serverDate(),
        },
    });
    await writeOperationLog({
        module: 'user_coupon',
        action: 'lock',
        targetId: couponId,
        targetName: coupon.templateName,
        operatorId: auth.openid,
        operatorName: auth.nickName || auth.openid,
        beforeData: { status: 'unused' },
        afterData: { status: 'locked', orderId, business: business || orderType },
    });
    return handleSuccess(null, '优惠券已锁定');
}
exports.lockCoupon = lockCoupon;
// =====================================================================
// Handler 6: useCoupon
// =====================================================================
async function useCoupon(event, _context, auth) {
    const { couponId, orderId, business, originalAmount, discountAmount, finalAmount } = event;
    if (!auth.openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    if (!couponId) {
        throw err('INVALID_PARAMS', '缺少优惠券ID');
    }
    const couponRes = await db.collection('user_coupons').where({ _id: couponId }).limit(1).get();
    if (couponRes.data.length === 0) {
        throw err('NOT_FOUND', '优惠券不存在');
    }
    const coupon = couponRes.data[0];
    if (coupon.ownerId !== auth.openid) {
        throw err('PERMISSION_DENIED', '无权操作此优惠券');
    }
    if (coupon.status !== 'locked') {
        throw err('COUPON_STATUS_INVALID', `当前状态: ${coupon.status}`);
    }
    await db.collection('user_coupons').doc(couponId).update({
        data: {
            status: 'used',
            usedAt: db.serverDate(),
            usedOrderId: orderId || '',
            usedBusiness: business || '',
            updatedAt: db.serverDate(),
        },
    });
    const usageRecord = {
        _id: generateId('coupon', auth.openid),
        userCouponId: couponId,
        templateId: coupon.templateId,
        ownerId: auth.openid,
        orderId: orderId || '',
        businessType: business || '',
        originalAmount: originalAmount || 0,
        discountAmount: discountAmount || 0,
        finalAmount: finalAmount || 0,
        usedAt: db.serverDate(),
        createdAt: db.serverDate(),
    };
    await db.collection('coupon_usage').add({ data: usageRecord });
    await writeOperationLog({
        module: 'user_coupon',
        action: 'use',
        targetId: couponId,
        targetName: coupon.templateName,
        operatorId: auth.openid,
        operatorName: auth.nickName || auth.openid,
        beforeData: { status: 'locked' },
        afterData: { status: 'used', orderId: orderId || '', discountAmount: discountAmount || 0 },
    });
    return handleSuccess(null, '优惠券已核销');
}
exports.useCoupon = useCoupon;
// =====================================================================
// Handler 7: unlockCoupon
// =====================================================================
async function unlockCoupon(event, _context, auth) {
    const { couponId } = event;
    if (!auth.openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    if (!couponId) {
        throw err('INVALID_PARAMS', '缺少优惠券ID');
    }
    const couponRes = await db.collection('user_coupons').where({ _id: couponId }).limit(1).get();
    if (couponRes.data.length === 0) {
        throw err('NOT_FOUND', '优惠券不存在');
    }
    const coupon = couponRes.data[0];
    if (coupon.ownerId !== auth.openid) {
        throw err('PERMISSION_DENIED', '无权操作此优惠券');
    }
    if (coupon.status !== 'locked') {
        throw err('COUPON_STATUS_INVALID', `当前状态: ${coupon.status}`);
    }
    const now = new Date();
    const isExpired = coupon.endTime ? new Date(coupon.endTime) < now : false;
    const newStatus = isExpired ? 'expired' : 'unused';
    await db.collection('user_coupons').doc(couponId).update({
        data: {
            status: newStatus,
            updatedAt: db.serverDate(),
        },
    });
    await writeOperationLog({
        module: 'user_coupon',
        action: 'unlock',
        targetId: couponId,
        targetName: coupon.templateName,
        operatorId: auth.openid,
        operatorName: auth.nickName || auth.openid,
        beforeData: { status: 'locked' },
        afterData: { status: newStatus },
    });
    return handleSuccess(null, isExpired ? '优惠券已过期' : '优惠券已退回');
}
exports.unlockCoupon = unlockCoupon;
// =====================================================================
// Handler 8: getPopupCoupon
// =====================================================================
async function getPopupCoupon(event, _context, auth) {
    const { page } = event;
    if (!auth.openid) {
        throw err('AUTH_REQUIRED', '未登录');
    }
    if (!page) {
        throw err('INVALID_PARAMS', '缺少页面标识');
    }
    const templates = await db.collection('coupon_templates')
        .where({ status: 'active', popupEnabled: true, popupPage: page, remaining: _.gt(0) })
        .orderBy('createdAt', 'desc')
        .limit(5)
        .get();
    if (!templates.data || templates.data.length === 0) {
        return handleSuccess(null);
    }
    // 检查用户是否已领取过
    const templateIds = templates.data.map((t) => t._id || '').filter(Boolean);
    const claimedRes = await db.collection('user_coupons')
        .where({ templateId: _.in(templateIds), ownerId: auth.openid, status: _.in(['unused', 'locked']) })
        .get();
    const claimedSet = new Set((claimedRes.data || []).map((c) => c.templateId));
    const available = templates.data.find((t) => !claimedSet.has(t._id));
    if (!available) {
        return handleSuccess(null);
    }
    const popup = {
        templateId: available._id,
        name: available.name,
        type: available.type,
        rules: available.rules,
        applicableScopes: available.applicableScopes,
        remaining: available.remaining,
        validDays: available.validDays,
        perUserLimit: available.perUserLimit,
        canClaim: true,
    };
    return handleSuccess(popup);
}
exports.getPopupCoupon = getPopupCoupon;
// =====================================================================
// Handlers 聚合
// =====================================================================
exports.handlers = {
    getMyCoupons,
    getAvailableCoupons,
    getClaimableTemplates,
    getPopupCoupon,
    claimCoupon,
    lockCoupon,
    useCoupon,
    unlockCoupon,
};
// =====================================================================
// Main 入口
// =====================================================================
async function main(event, context) {
    const { action } = event;
    if (!action || !exports.handlers[action]) {
        throw err('INVALID_PARAMS', '无效的操作类型');
    }
    try {
        const auth = await verifyAuth(event, context);
        if (auth.error) {
            return auth;
        }
        logger.info(`[${action}]`, { ownerId: auth.openid });
        return await exports.handlers[action](event, context, auth);
    }
    catch (error) {
        logger.error(`[${action}]`, error);
        // 透传 BusinessError 错误码
        const e = error;
        if (e && e.code && e.severity) {
            const numericCode = ERROR_CODES[e.severity] || ERROR_CODES.BUSINESS;
            return handleError(error, e.message || '操作失败', numericCode);
        }
        return handleError(error, e.message || '服务器错误', ERROR_CODES.SERVER);
    }
}
exports.main = main;
// =====================================================================
// Runtime shim（CommonJS 兼容）
// =====================================================================
const _mod = module;
_mod.exports = {
    main,
    getMyCoupons,
    getAvailableCoupons,
    getClaimableTemplates,
    getPopupCoupon,
    claimCoupon,
    lockCoupon,
    useCoupon,
    unlockCoupon,
    calculateCouponDiscount,
    generateCouponCode,
    handlers: exports.handlers,
};
_mod.exports.default = _mod.exports;
exports.default = {
    main,
    getMyCoupons,
    getAvailableCoupons,
    getClaimableTemplates,
    getPopupCoupon,
    claimCoupon,
    lockCoupon,
    useCoupon,
    unlockCoupon,
    calculateCouponDiscount,
    generateCouponCode,
    handlers: exports.handlers,
};
